export const VOICE_NAME = 'lovely_girl';

export const VOICE_LINES = {
  welcome: { text: "Hello! I'm Foxy. Let's play together!", emotion: 'happy' },
  guide_again: { text: "Let's listen again.", emotion: 'calm' },
  guide_together: { text: "Let's do it together.", emotion: 'happy' },
  guide_say: { text: 'Say it with me.', emotion: 'happy' },
  reward_done: { text: 'We did it! High five!', emotion: 'happy' },

  word_hello: { text: 'Hello!', speed: 0.82, emotion: 'happy' },
  word_bye: { text: 'Bye-bye!', speed: 0.82, emotion: 'happy' },
  word_apple: { text: 'Apple.', speed: 0.82, emotion: 'fluent' },
  word_ball: { text: 'Ball.', speed: 0.82, emotion: 'fluent' },
  word_cat: { text: 'Cat.', speed: 0.82, emotion: 'fluent' },
  word_dog: { text: 'Dog.', speed: 0.82, emotion: 'fluent' },
  word_car: { text: 'Car.', speed: 0.82, emotion: 'fluent' },
  word_milk: { text: 'Milk.', speed: 0.82, emotion: 'fluent' },

  yes_hello: { text: 'Hello, friend!', emotion: 'happy' },
  yes_bye: { text: 'Bye-bye! See you soon!', emotion: 'happy' },
  yes_apple: { text: 'Yes! Apple!', emotion: 'happy' },
  yes_ball: { text: 'Yes! Ball!', emotion: 'happy' },
  yes_cat: { text: 'Yes! Cat!', emotion: 'happy' },
  yes_dog: { text: 'Yes! Dog!', emotion: 'happy' },
  yes_car: { text: 'Yes! Car!', emotion: 'happy' },
  yes_milk: { text: 'Yes! Milk!', emotion: 'happy' },

  prompt_tap_foxy: { text: 'Tap Foxy. Hello!', emotion: 'happy' },
  prompt_find_foxy: { text: 'Find Foxy. Hello!', emotion: 'happy' },
  prompt_bye: { text: 'Tap the house. Bye-bye!', emotion: 'calm' },
  prompt_find_apple: { text: 'Find the apple.', emotion: 'fluent' },
  prompt_find_ball: { text: 'Find the ball.', emotion: 'fluent' },
  prompt_find_cat: { text: 'Find the cat.', emotion: 'fluent' },
  prompt_find_dog: { text: 'Find the dog.', emotion: 'fluent' },
  prompt_find_car: { text: 'Find the car.', emotion: 'fluent' },
  prompt_find_milk: { text: 'Find the milk.', emotion: 'fluent' },
  prompt_give_apple: { text: 'Give me the apple.', emotion: 'happy' },
  prompt_give_ball: { text: 'Give me the ball.', emotion: 'happy' },
  prompt_give_cat: { text: 'Give me the cat.', emotion: 'happy' },
  prompt_give_dog: { text: 'Give me the dog.', emotion: 'happy' },
  prompt_give_car: { text: 'Give me the car.', emotion: 'happy' },
  prompt_give_milk: { text: 'Give me the milk.', emotion: 'happy' },

  m01_story: { text: "Hello! Hello! I'm Foxy.", emotion: 'happy' },
  m02_story: { text: 'Hello? Can you find me? Hello!', emotion: 'happy' },
  m03_story: { text: 'The moon is here. Bye-bye, Foxy!', emotion: 'calm' },
  m04_story: { text: 'Look! An apple. Apple!', emotion: 'happy' },
  m05_story: { text: 'Oh! The ball rolled away. Ball!', emotion: 'surprised' },
  m06_story: { text: 'Our basket needs a treasure. Listen!', emotion: 'happy' },
  m07_story: { text: 'Meow! A cat is hiding. Cat!', emotion: 'happy' },
  m08_story: { text: 'Woof! The dog needs help. Dog!', emotion: 'happy' },
  m09_story: { text: 'Cat and dog need their signs. Listen!', emotion: 'happy' },
  m10_story: { text: 'Beep beep! Here comes the car. Car!', emotion: 'happy' },
  m11_story: { text: 'Bunny is thirsty. Milk!', emotion: 'happy' },
  m12_story: { text: "The treasures are hiding. Let's find them!", emotion: 'happy' },
  m13_story: { text: 'It is dark. Shine the light and listen!', emotion: 'calm' },
  m14_story: { text: 'Our friends need gifts. Listen and give!', emotion: 'happy' },
  m15_story: { text: "The garden party is almost ready. Let's help!", emotion: 'happy' },
};

export const ITEMS = {
  fox: {
    id: 'fox', emoji: '🦊', label: 'Foxy', display: 'Hello!', audio: 'word_hello', successAudio: 'yes_hello', tone: 'orange',
  },
  home: {
    id: 'home', emoji: '🏡', label: 'home', display: 'Bye-bye!', audio: 'word_bye', successAudio: 'yes_bye', tone: 'blue',
  },
  apple: {
    id: 'apple', emoji: '🍎', label: 'apple', display: 'apple', audio: 'word_apple', successAudio: 'yes_apple', tone: 'red',
  },
  ball: {
    id: 'ball', emoji: '⚽', label: 'ball', display: 'ball', audio: 'word_ball', successAudio: 'yes_ball', tone: 'yellow',
  },
  cat: {
    id: 'cat', emoji: '🐱', label: 'cat', display: 'cat', audio: 'word_cat', successAudio: 'yes_cat', tone: 'purple',
  },
  dog: {
    id: 'dog', emoji: '🐶', label: 'dog', display: 'dog', audio: 'word_dog', successAudio: 'yes_dog', tone: 'green',
  },
  car: {
    id: 'car', emoji: '🚗', label: 'car', display: 'car', audio: 'word_car', successAudio: 'yes_car', tone: 'blue',
  },
  milk: {
    id: 'milk', emoji: '🥛', label: 'milk', display: 'milk', audio: 'word_milk', successAudio: 'yes_milk', tone: 'cream',
  },
};

const round = (target, choices, audio, prompt, mode = 'find') => ({ target, choices, audio, prompt, mode });

export const MISSIONS = [
  {
    id: 1,
    stage: 0,
    title: '小狐醒来了',
    english: 'Hello!',
    icon: '🌞',
    storyGoal: '轻轻叫醒小狐，成为她的第一个朋友',
    scene: ['🌤️', '🛏️', '🦊'],
    introAudio: 'm01_story',
    meet: ['fox'],
    meetRepeats: 3,
    rounds: [round('fox', ['fox'], 'prompt_tap_foxy', 'Hello!', 'wake')],
    echo: 'fox',
    worldChange: '小狐的窗户亮起来了',
    worldEmoji: '🏡✨',
    keepsake: { emoji: '👋', title: 'Hello 小手' },
    familyQuest: '见到家人时挥挥手，说 “Hello!”',
  },
  {
    id: 2,
    stage: 0,
    title: '回声树洞',
    english: 'Hello?',
    icon: '🌳',
    storyGoal: '听回声，把藏起来的小狐找出来',
    scene: ['🌲', '🕳️', '🌼'],
    introAudio: 'm02_story',
    meet: ['fox'],
    meetRepeats: 2,
    rounds: [round('fox', ['fox'], 'prompt_find_foxy', 'Hello!', 'reveal')],
    echo: 'fox',
    worldChange: '树洞旁开出三朵回声花',
    worldEmoji: '🌳🌼',
    keepsake: { emoji: '🌼', title: '回声花' },
    familyQuest: '躲到门后说 “Hello”，让孩子来找你',
  },
  {
    id: 3,
    stage: 0,
    title: '晚安小路',
    english: 'Bye-bye!',
    icon: '🌙',
    storyGoal: '陪小狐走回家，挥手说再见',
    scene: ['🌙', '👣', '🏡'],
    introAudio: 'm03_story',
    meet: ['home'],
    meetRepeats: 3,
    rounds: [round('home', ['home'], 'prompt_bye', 'Bye-bye!', 'path')],
    echo: 'home',
    worldChange: '通往宝物花园的大门打开了',
    worldEmoji: '🚪🌟',
    keepsake: { emoji: '🌙', title: '月亮路灯' },
    familyQuest: '睡前和玩具挥挥手，说 “Bye-bye!”',
  },
  {
    id: 4,
    stage: 1,
    title: '苹果树醒来',
    english: 'Apple',
    icon: '🍎',
    storyGoal: '叫醒苹果树，让第一颗苹果落下来',
    scene: ['🌳', '🌱', '🦊'],
    introAudio: 'm04_story',
    meet: ['apple'],
    meetRepeats: 3,
    rounds: [round('apple', ['apple'], 'prompt_find_apple', 'Find the apple.', 'drop')],
    echo: 'apple',
    worldChange: '花园里长出第一棵苹果树',
    worldEmoji: '🌳🍎',
    keepsake: { emoji: '🍎', title: '第一颗苹果' },
    familyQuest: '吃水果时拿起苹果，说 “Apple.”',
  },
  {
    id: 5,
    stage: 1,
    title: '滚走的小球',
    english: 'Ball',
    icon: '⚽',
    storyGoal: '找到滚走的小球，把它送回篮子旁',
    scene: ['⛰️', '〰️', '🧺'],
    introAudio: 'm05_story',
    meet: ['ball'],
    meetRepeats: 3,
    rounds: [round('ball', ['apple', 'ball'], 'prompt_find_ball', 'Find the ball.', 'roll')],
    echo: 'ball',
    worldChange: '草坡上出现一条彩色球道',
    worldEmoji: '🌈⚽',
    keepsake: { emoji: '⚽', title: '滚滚小球' },
    familyQuest: '把球和另一个玩具放一起，说 “Ball.”',
  },
  {
    id: 6,
    stage: 1,
    title: '篮子里的宝物',
    english: 'Apple or ball?',
    icon: '🧺',
    storyGoal: '听声音，把两件宝物放进野餐篮',
    scene: ['🧺', '🍎', '⚽'],
    introAudio: 'm06_story',
    meet: ['apple', 'ball'],
    meetRepeats: 1,
    rounds: [
      round('apple', ['ball', 'apple'], 'prompt_find_apple', 'Find the apple.', 'pack'),
      round('ball', ['apple', 'ball'], 'prompt_find_ball', 'Find the ball.', 'pack'),
    ],
    echo: 'apple',
    worldChange: '野餐篮系上了漂亮的蝴蝶结',
    worldEmoji: '🧺🎀',
    keepsake: { emoji: '🎀', title: '宝物蝴蝶结' },
    familyQuest: '轮流说 “Apple” 和 “Ball”，让孩子指一指',
  },
  {
    id: 7,
    stage: 1,
    title: '草丛里的小猫',
    english: 'Cat',
    icon: '🐱',
    storyGoal: '听着喵喵声，把藏在草丛里的朋友找到',
    scene: ['🌿', '🌿', '🐾'],
    introAudio: 'm07_story',
    meet: ['cat'],
    meetRepeats: 3,
    rounds: [round('cat', ['apple', 'cat'], 'prompt_find_cat', 'Find the cat.', 'reveal')],
    echo: 'cat',
    worldChange: '小猫搬进了花园的小帐篷',
    worldEmoji: '⛺🐱',
    keepsake: { emoji: '🐾', title: '猫咪脚印' },
    familyQuest: '看到猫咪图片时，轻轻说 “Cat.”',
  },
  {
    id: 8,
    stage: 1,
    title: '泥坑小狗',
    english: 'Dog',
    icon: '🐶',
    storyGoal: '找到小狗，为它铺一条离开泥坑的小路',
    scene: ['☁️', '🟤', '👣'],
    introAudio: 'm08_story',
    meet: ['dog'],
    meetRepeats: 3,
    rounds: [round('dog', ['cat', 'dog'], 'prompt_find_dog', 'Find the dog.', 'rescue')],
    echo: 'dog',
    worldChange: '小狗洗干净，住进了花园',
    worldEmoji: '🫧🐶',
    keepsake: { emoji: '🫧', title: '泡泡毛巾' },
    familyQuest: '把猫和狗的图片放一起，说 “Dog.”',
  },
  {
    id: 9,
    stage: 1,
    title: '谁在叫我',
    english: 'Cat or dog?',
    icon: '🪧',
    storyGoal: '听一听，帮小猫和小狗找到自己的路牌',
    scene: ['🐱', '🪧', '🐶'],
    introAudio: 'm09_story',
    meet: ['cat', 'dog'],
    meetRepeats: 1,
    rounds: [
      round('cat', ['dog', 'cat'], 'prompt_find_cat', 'Find the cat.', 'sign'),
      round('dog', ['cat', 'dog'], 'prompt_find_dog', 'Find the dog.', 'sign'),
    ],
    echo: 'cat',
    worldChange: '两块动物路牌立在花园路口',
    worldEmoji: '🪧🐾',
    keepsake: { emoji: '🪧', title: '朋友路牌' },
    familyQuest: '说 “Cat” 或 “Dog”，孩子用动作模仿它',
  },
  {
    id: 10,
    stage: 1,
    title: '小车出发',
    english: 'Car',
    icon: '🚗',
    storyGoal: '找到小车，让它沿着新轨道开进花园',
    scene: ['🛤️', '🔧', '🏁'],
    introAudio: 'm10_story',
    meet: ['car'],
    meetRepeats: 3,
    rounds: [round('car', ['ball', 'car'], 'prompt_find_car', 'Find the car.', 'drive')],
    echo: 'car',
    worldChange: '一条小车轨道绕过花园',
    worldEmoji: '🛤️🚗',
    keepsake: { emoji: '🏁', title: '花园车票' },
    familyQuest: '玩小车时，让它出发并说 “Car.”',
  },
  {
    id: 11,
    stage: 1,
    title: '兔子的杯子',
    english: 'Milk',
    icon: '🥛',
    storyGoal: '找到牛奶，为口渴的兔子倒满杯子',
    scene: ['🐰', '🥤', '🌤️'],
    introAudio: 'm11_story',
    meet: ['milk'],
    meetRepeats: 3,
    rounds: [round('milk', ['apple', 'milk'], 'prompt_find_milk', 'Find the milk.', 'pour')],
    echo: 'milk',
    worldChange: '兔子的杯子变成花园小喷泉',
    worldEmoji: '🥛⛲',
    keepsake: { emoji: '🥛', title: '兔子牛奶杯' },
    familyQuest: '喝奶时举起杯子，说 “Milk.”',
  },
  {
    id: 12,
    stage: 1,
    title: '宝物躲猫猫',
    english: 'Treasure hunt',
    icon: '🎁',
    storyGoal: '在换过位置的盒子里找到六种熟悉宝物',
    scene: ['🎁', '❔', '🎁'],
    introAudio: 'm12_story',
    meet: ['apple', 'ball', 'cat', 'dog', 'car', 'milk'],
    meetRepeats: 1,
    rounds: [
      round('apple', ['ball', 'apple'], 'prompt_find_apple', 'Find the apple.', 'hide'),
      round('dog', ['cat', 'dog'], 'prompt_find_dog', 'Find the dog.', 'hide'),
      round('milk', ['car', 'milk'], 'prompt_find_milk', 'Find the milk.', 'hide'),
    ],
    echo: 'ball',
    worldChange: '花园里挂起一排宝物彩旗',
    worldEmoji: '🎏🎁',
    keepsake: { emoji: '🗝️', title: '宝物钥匙' },
    familyQuest: '从 apple、ball、cat 中任选两个玩听音寻找',
  },
  {
    id: 13,
    stage: 1,
    title: '夜晚手电筒',
    english: 'Listen in the dark',
    icon: '🔦',
    storyGoal: '在没有发光提示的夜晚，用耳朵寻找目标',
    scene: ['🌌', '🔦', '✨'],
    introAudio: 'm13_story',
    meet: ['cat', 'car', 'dog'],
    meetRepeats: 1,
    rounds: [
      round('cat', ['dog', 'car', 'cat'], 'prompt_find_cat', 'Find the cat.', 'flashlight'),
      round('car', ['cat', 'car', 'dog'], 'prompt_find_car', 'Find the car.', 'flashlight'),
      round('dog', ['car', 'dog', 'cat'], 'prompt_find_dog', 'Find the dog.', 'flashlight'),
    ],
    echo: 'cat',
    worldChange: '星星灯笼照亮了花园夜路',
    worldEmoji: '🏮⭐',
    keepsake: { emoji: '🔦', title: '星光手电筒' },
    familyQuest: '关小灯，用手电照两个玩具，说出其中一个英文',
  },
  {
    id: 14,
    stage: 1,
    title: '给朋友送礼物',
    english: 'Give me…',
    icon: '🎀',
    storyGoal: '听声音，把三件礼物送到朋友手中',
    scene: ['🐰', '🎁', '🦊'],
    introAudio: 'm14_story',
    meet: ['apple', 'ball', 'milk'],
    meetRepeats: 1,
    rounds: [
      round('ball', ['apple', 'ball', 'milk'], 'prompt_give_ball', 'Give me the ball.', 'gift'),
      round('milk', ['ball', 'milk', 'apple'], 'prompt_give_milk', 'Give me the milk.', 'gift'),
      round('apple', ['milk', 'apple', 'ball'], 'prompt_give_apple', 'Give me the apple.', 'gift'),
    ],
    echo: 'milk',
    worldChange: '庆典礼物桌摆满彩色礼盒',
    worldEmoji: '🎁🎀',
    keepsake: { emoji: '🎁', title: '朋友礼物盒' },
    familyQuest: '拿两件熟悉物品，说 “Give me the ball.”',
  },
  {
    id: 15,
    stage: 1,
    title: '花园庆典',
    english: 'Garden party!',
    icon: '🎉',
    storyGoal: '听懂三个线索，和所有朋友一起点亮庆典',
    scene: ['🎪', '🎈', '🎊'],
    introAudio: 'm15_story',
    meet: ['car', 'cat', 'milk'],
    meetRepeats: 1,
    rounds: [
      round('car', ['milk', 'cat', 'car'], 'prompt_find_car', 'Find the car.', 'festival'),
      round('cat', ['car', 'cat', 'milk'], 'prompt_find_cat', 'Find the cat.', 'festival'),
      round('milk', ['cat', 'milk', 'car'], 'prompt_find_milk', 'Find the milk.', 'festival'),
    ],
    echo: 'fox',
    worldChange: '宝物花园变成闪闪发光的庆典舞台',
    worldEmoji: '🎪🌈🎉',
    keepsake: { emoji: '🏆', title: '花园小英雄' },
    familyQuest: '从六个熟悉词中任选三个，玩一次家庭寻宝',
  },
];

export const STAGES = [
  {
    id: 0,
    title: '小狐之家',
    english: 'Foxy Home',
    icon: '🏡',
    description: '先学会听声音、点一点击和回到地图',
    color: '#ff9f68',
  },
  {
    id: 1,
    title: '宝物花园',
    english: 'Treasure Garden',
    icon: '🌼',
    description: '用耳朵认识 apple、ball、cat、dog、car 和 milk',
    color: '#63c982',
  },
];

export function getMission(id) {
  return MISSIONS.find((mission) => mission.id === id);
}

export function getVoiceText(key) {
  return VOICE_LINES[key]?.text || '';
}
