export const VOICE_NAME = 'lovely_girl';

export const VOICE_LINES = {
  welcome: { text: "Hello! I'm Foxy. Let's play together!", emotion: 'happy' },
  guide_again: { text: "Let's listen again.", emotion: 'calm' },
  guide_together: { text: "Let's do it together.", emotion: 'happy' },
  guide_say: { text: 'Say it with me.', emotion: 'happy' },
  reward_done: { text: 'We did it! High five!', emotion: 'happy' },

  zh_welcome: { text: '你好呀，我是小狐。点一下，我们一起去冒险吧！', language: 'Chinese', speed: 0.92, emotion: 'happy' },
  zh_meet: { text: '点一点，听一听。', language: 'Chinese', speed: 0.9, emotion: 'happy' },
  zh_listen_choose: { text: '仔细听，然后点一下你听到的。', language: 'Chinese', speed: 0.9, emotion: 'calm' },
  zh_try_again: { text: '没关系，我们再听一次。', language: 'Chinese', speed: 0.9, emotion: 'calm' },
  zh_together: { text: '我来陪你一起完成。', language: 'Chinese', speed: 0.92, emotion: 'happy' },
  zh_echo: { text: '想说就跟着说，不想说也可以继续。', language: 'Chinese', speed: 0.9, emotion: 'calm' },
  zh_reward: { text: '太棒了！你帮助了小狐！', language: 'Chinese', speed: 0.92, emotion: 'happy' },
  zh_story_next: { text: '故事听完啦，点下面的大手，我们出发吧！', language: 'Chinese', speed: 0.92, emotion: 'happy' },
  zh_meet_done: { text: '都听完啦，点下面的耳朵，开始游戏吧！', language: 'Chinese', speed: 0.92, emotion: 'happy' },
  zh_give_finish: { text: '拿对啦！再点一下朋友，把它递过去。', language: 'Chinese', speed: 0.9, emotion: 'happy' },
  zh_put_finish: { text: '拿对啦！再点一下闪亮的地方，把它放进去。', language: 'Chinese', speed: 0.9, emotion: 'happy' },
  zh_echo_detail: { text: '先点喇叭听一遍。想说就说，不想说就点挥挥手。', language: 'Chinese', speed: 0.88, emotion: 'calm' },
  zh_reward_next: { text: '太棒了！点地图回去，或者今天先休息。', language: 'Chinese', speed: 0.9, emotion: 'happy' },
  zh_wait_help: { text: '再点一下喇叭听一遍，然后点你听到的图片。', language: 'Chinese', speed: 0.88, emotion: 'calm' },
  zh_story_order: { text: '故事开始啦，仔细听，一步一步帮助朋友。', language: 'Chinese', speed: 0.9, emotion: 'happy' },

  word_hello: { text: 'Hello!', speed: 0.82, emotion: 'happy' },
  word_bye: { text: 'Bye-bye!', speed: 0.82, emotion: 'happy' },
  word_apple: { text: 'Apple.', speed: 0.82, emotion: 'fluent' },
  word_ball: { text: 'Ball.', speed: 0.82, emotion: 'fluent' },
  word_cat: { text: 'Cat.', speed: 0.82, emotion: 'fluent' },
  word_dog: { text: 'Dog.', speed: 0.82, emotion: 'fluent' },
  word_car: { text: 'Car.', speed: 0.82, emotion: 'fluent' },
  word_milk: { text: 'Milk.', speed: 0.82, emotion: 'fluent' },
  word_find: { text: 'Find it!', speed: 0.84, emotion: 'happy' },
  word_give: { text: 'Give it to me!', speed: 0.84, emotion: 'happy' },
  word_put: { text: 'Put it in!', speed: 0.84, emotion: 'happy' },
  word_jump: { text: 'Jump!', speed: 0.82, emotion: 'happy' },
  word_stop: { text: 'Stop!', speed: 0.82, emotion: 'calm' },
  word_red: { text: 'Red.', speed: 0.82, emotion: 'fluent' },
  word_blue: { text: 'Blue.', speed: 0.82, emotion: 'fluent' },
  word_red_apple: { text: 'Red apple.', speed: 0.82, emotion: 'fluent' },
  word_blue_ball: { text: 'Blue ball.', speed: 0.82, emotion: 'fluent' },
  word_red_ball: { text: 'Red ball.', speed: 0.82, emotion: 'fluent' },
  word_blue_apple: { text: 'Blue apple.', speed: 0.82, emotion: 'fluent' },
  word_big: { text: 'Big.', speed: 0.82, emotion: 'fluent' },
  word_small: { text: 'Small.', speed: 0.82, emotion: 'fluent' },
  word_big_dog: { text: 'Big dog.', speed: 0.82, emotion: 'fluent' },
  word_small_cat: { text: 'Small cat.', speed: 0.82, emotion: 'fluent' },
  word_i_want: { text: 'I want...', speed: 0.82, emotion: 'fluent' },
  word_want_apple: { text: 'I want an apple.', speed: 0.82, emotion: 'happy' },
  word_want_ball: { text: 'I want a ball.', speed: 0.82, emotion: 'happy' },
  word_want_milk: { text: 'I want milk.', speed: 0.82, emotion: 'happy' },
  word_here_you_are: { text: 'Here you are.', speed: 0.82, emotion: 'happy' },
  word_thank_you: { text: 'Thank you!', speed: 0.82, emotion: 'happy' },
  word_i_like: { text: 'I like...', speed: 0.82, emotion: 'fluent' },
  word_like_apples: { text: 'I like apples.', speed: 0.82, emotion: 'happy' },
  word_like_cats: { text: 'I like cats.', speed: 0.82, emotion: 'happy' },
  word_like_milk: { text: 'I like milk.', speed: 0.82, emotion: 'happy' },
  word_im_happy: { text: "I'm happy!", speed: 0.82, emotion: 'happy' },

  yes_hello: { text: 'Hello, friend!', emotion: 'happy' },
  yes_bye: { text: 'Bye-bye! See you soon!', emotion: 'happy' },
  yes_apple: { text: 'Yes! Apple!', emotion: 'happy' },
  yes_ball: { text: 'Yes! Ball!', emotion: 'happy' },
  yes_cat: { text: 'Yes! Cat!', emotion: 'happy' },
  yes_dog: { text: 'Yes! Dog!', emotion: 'happy' },
  yes_car: { text: 'Yes! Car!', emotion: 'happy' },
  yes_milk: { text: 'Yes! Milk!', emotion: 'happy' },
  yes_find: { text: 'You found it! Great job!', emotion: 'happy' },
  yes_give: { text: 'Thank you! You gave it to me!', emotion: 'happy' },
  yes_put: { text: 'In it goes! Great job!', emotion: 'happy' },
  yes_jump: { text: 'Jump, jump! Great job!', emotion: 'happy' },
  yes_stop: { text: 'Yes! Stop!', emotion: 'happy' },
  yes_red: { text: 'Yes! Red!', emotion: 'happy' },
  yes_blue: { text: 'Yes! Blue!', emotion: 'happy' },
  yes_red_apple: { text: 'Yes! Red apple!', emotion: 'happy' },
  yes_blue_ball: { text: 'Yes! Blue ball!', emotion: 'happy' },
  yes_red_ball: { text: 'Yes! Red ball!', emotion: 'happy' },
  yes_blue_apple: { text: 'Yes! Blue apple!', emotion: 'happy' },
  yes_big: { text: 'Yes! Big!', emotion: 'happy' },
  yes_small: { text: 'Yes! Small!', emotion: 'happy' },
  yes_big_dog: { text: 'Yes! Big dog!', emotion: 'happy' },
  yes_small_cat: { text: 'Yes! Small cat!', emotion: 'happy' },
  yes_i_want: { text: 'I know what I want!', emotion: 'happy' },
  yes_want_apple: { text: 'Yes! I want an apple!', emotion: 'happy' },
  yes_want_ball: { text: 'Yes! I want a ball!', emotion: 'happy' },
  yes_want_milk: { text: 'Yes! I want milk!', emotion: 'happy' },
  yes_here_you_are: { text: 'Here you are! For you!', emotion: 'happy' },
  yes_thank_you: { text: 'Thank you, my friend!', emotion: 'happy' },
  yes_i_like: { text: 'Yes! I like it!', emotion: 'happy' },
  yes_like_apples: { text: 'Yes! I like apples!', emotion: 'happy' },
  yes_like_cats: { text: 'Yes! I like cats!', emotion: 'happy' },
  yes_like_milk: { text: 'Yes! I like milk!', emotion: 'happy' },
  yes_im_happy: { text: "Hooray! I'm happy!", emotion: 'happy' },

  prompt_tap_foxy: { text: 'Tap Foxy. Hello!', emotion: 'happy' },
  prompt_find_foxy: { text: 'Find Foxy. Hello!', emotion: 'happy' },
  prompt_bye: { text: 'Tap the house. Bye-bye!', emotion: 'calm' },
  prompt_find_apple: { text: 'Find the apple.', emotion: 'fluent' },
  prompt_find_ball: { text: 'Find the ball.', emotion: 'fluent' },
  prompt_find_cat: { text: 'Find the cat.', emotion: 'fluent' },
  prompt_find_dog: { text: 'Find the dog.', emotion: 'fluent' },
  prompt_find_car: { text: 'Find the car.', emotion: 'fluent' },
  prompt_find_milk: { text: 'Find the milk.', emotion: 'fluent' },
  prompt_give_apple: { text: 'Give me the apple.', emotion: 'happy' },
  prompt_give_ball: { text: 'Give me the ball.', emotion: 'happy' },
  prompt_give_cat: { text: 'Give me the cat.', emotion: 'happy' },
  prompt_give_dog: { text: 'Give me the dog.', emotion: 'happy' },
  prompt_give_car: { text: 'Give me the car.', emotion: 'happy' },
  prompt_give_milk: { text: 'Give me the milk.', emotion: 'happy' },
  prompt_put_apple: { text: 'Put the apple in.', emotion: 'happy' },
  prompt_put_ball: { text: 'Put the ball in.', emotion: 'happy' },
  prompt_put_car: { text: 'Put the car in.', emotion: 'happy' },
  prompt_put_milk: { text: 'Put the milk in.', emotion: 'happy' },
  prompt_jump: { text: 'Jump!', emotion: 'happy' },
  prompt_stop: { text: 'Stop!', emotion: 'calm' },
  prompt_red_apple: { text: 'Find the red apple.', emotion: 'fluent' },
  prompt_blue_ball: { text: 'Find the blue ball.', emotion: 'fluent' },
  prompt_red_ball: { text: 'Find the red ball.', emotion: 'fluent' },
  prompt_blue_apple: { text: 'Find the blue apple.', emotion: 'fluent' },
  prompt_big_dog: { text: 'Find the big dog.', emotion: 'fluent' },
  prompt_small_cat: { text: 'Find the small cat.', emotion: 'fluent' },
  prompt_want_apple: { text: 'I want an apple.', emotion: 'happy' },
  prompt_want_ball: { text: 'I want a ball.', emotion: 'happy' },
  prompt_want_milk: { text: 'I want milk.', emotion: 'happy' },
  prompt_here_you_are: { text: 'Here you are.', emotion: 'happy' },
  prompt_here_apple: { text: 'Here you are. An apple for you.', emotion: 'happy' },
  prompt_here_ball: { text: 'Here you are. A ball for you.', emotion: 'happy' },
  prompt_here_milk: { text: 'Here you are. Milk for you.', emotion: 'happy' },
  prompt_thank_you: { text: 'Thank you!', emotion: 'happy' },
  prompt_like_apples: { text: 'I like apples.', emotion: 'happy' },
  prompt_like_cats: { text: 'I like cats.', emotion: 'happy' },
  prompt_like_milk: { text: 'I like milk.', emotion: 'happy' },
  prompt_im_happy: { text: "I'm happy!", emotion: 'happy' },

  m01_story: { text: "Hello! Hello! I'm Foxy.", emotion: 'happy' },
  m02_story: { text: 'Hello? Can you find me? Hello!', emotion: 'happy' },
  m03_story: { text: 'The moon is here. Bye-bye, Foxy!', emotion: 'calm' },
  m04_story: { text: 'Look! An apple. Apple!', emotion: 'happy' },
  m05_story: { text: 'Oh! The ball rolled away. Ball!', emotion: 'surprised' },
  m06_story: { text: 'Our basket needs a treasure. Listen!', emotion: 'happy' },
  m07_story: { text: 'Meow! A cat is hiding. Cat!', emotion: 'happy' },
  m08_story: { text: 'Woof! The dog needs help. Dog!', emotion: 'happy' },
  m09_story: { text: 'Cat and dog need their signs. Listen!', emotion: 'happy' },
  m10_story: { text: 'Beep beep! Here comes the car. Car!', emotion: 'happy' },
  m11_story: { text: 'Bunny is thirsty. Milk!', emotion: 'happy' },
  m12_story: { text: "The treasures are hiding. Let's find them!", emotion: 'happy' },
  m13_story: { text: 'It is dark. Shine the light and listen!', emotion: 'calm' },
  m14_story: { text: 'Our friends need gifts. Listen and give!', emotion: 'happy' },
  m15_story: { text: "The garden party is almost ready. Let's help!", emotion: 'happy' },
  m16_story: { text: 'The forest signs are hiding. Find the apple!', emotion: 'happy' },
  m17_story: { text: 'Squirrel is packing a picnic. Give me the ball!', emotion: 'happy' },
  m18_story: { text: 'The little car needs a garage. Put the car in!', emotion: 'happy' },
  m19_story: { text: 'The mushrooms are bouncy. Jump!', emotion: 'happy' },
  m20_story: { text: 'The leaves are rushing toward the bridge. Stop!', emotion: 'surprised' },
  m21_story: { text: 'The forest path has two magic moves. Jump... and stop!', emotion: 'happy' },
  m22_story: { text: 'The berry lantern needs its color. Red!', emotion: 'happy' },
  m23_story: { text: 'The little stream wants a ribbon. Blue!', emotion: 'happy' },
  m24_story: { text: 'Red and blue stones can wake the bridge!', emotion: 'happy' },
  m25_story: { text: 'The campsite is messy. Put the treasures in!', emotion: 'happy' },
  m26_story: { text: 'The forest friends are waiting for their gifts!', emotion: 'happy' },
  m27_story: { text: 'The firefly show is ready. Listen and move!', emotion: 'happy' },
  m28_story: { text: 'The apple path is waiting. Find the red apple!', emotion: 'happy' },
  m29_story: { text: 'The windmill needs a blue ball. Find the blue ball!', emotion: 'happy' },
  m30_story: { text: 'The colors jumped to new treasures. Listen carefully!', emotion: 'surprised' },
  m31_story: { text: 'Whose footprints are so big? Find the big dog!', emotion: 'happy' },
  m32_story: { text: 'A tiny door is hiding. Find the small cat!', emotion: 'happy' },
  m33_story: { text: 'Bunny is at the milk shop. I want milk!', emotion: 'happy' },
  m34_story: { text: 'The toy cart is here. I want a ball!', emotion: 'happy' },
  m35_story: { text: 'The fruit stand is open. I want an apple!', emotion: 'happy' },
  m36_story: { text: 'Three shops, three wishes. Listen and choose!', emotion: 'happy' },
  m37_story: { text: 'Foxy has a gift for Bunny. Here you are!', emotion: 'happy' },
  m38_story: { text: 'The picnic friends are sharing. Here you are!', emotion: 'happy' },
  m39_story: { text: 'The kindness train is ready. Pass each gift along!', emotion: 'happy' },
  m40_story: { text: 'The thank-you bell is quiet. Thank you!', emotion: 'happy' },
  m41_story: { text: 'Kind words make the flower garden grow. Thank you!', emotion: 'happy' },
  m42_story: { text: "Welcome to Foxy's little shop. Let's talk together!", emotion: 'happy' },
  m43_story: { text: 'The picnic table needs a favorite. I like apples!', emotion: 'happy' },
  m44_story: { text: 'The cat cafe has a new friend. I like cats!', emotion: 'happy' },
  m45_story: { text: 'Everyone likes something different. Listen!', emotion: 'happy' },
  m46_story: { text: "The happy fountain wakes up with a smile. I'm happy!", emotion: 'happy' },
  m47_story: { text: "The town festival is starting. Let's talk and celebrate!", emotion: 'happy' },
  m48_story: { text: 'The castle gate is asleep. Say hello and find the red apple!', emotion: 'happy' },
  m49_story: { text: "The royal picnic basket is empty. Let's fill it!", emotion: 'happy' },
  m50_story: { text: 'A small cat is lost by the windy gate. Help her get home!', emotion: 'calm' },
  m51_story: { text: 'The moon garage needs a car and a blue ball. Listen!', emotion: 'calm' },
  m52_story: { text: 'The little dragon is hungry. I want milk!', emotion: 'happy' },
  m53_story: { text: "The rainbow room mixed up all its colors. Let's sort them!", emotion: 'surprised' },
  m54_story: { text: 'Two doors, two friends. Big dog and small cat need help!', emotion: 'happy' },
  m55_story: { text: 'The crown is flying away! Jump... stop... and catch it!', emotion: 'surprised' },
  m56_story: { text: "The castle shop is open. Let's ask, share, and say thank you!", emotion: 'happy' },
  m57_story: { text: 'The secret garden needs three little helpers. Listen carefully!', emotion: 'calm' },
  m58_story: { text: 'The party guests are choosing favorites. What do they like?', emotion: 'happy' },
  m59_story: { text: 'The Friendship Star is ready. One last adventure together!', emotion: 'happy' },
};

export const ITEMS = {
  fox: {
    id: 'fox', emoji: '🦊', label: 'Foxy', display: 'Hello!', audio: 'word_hello', successAudio: 'yes_hello', tone: 'orange',
  },
  home: {
    id: 'home', emoji: '🏡', label: 'home', display: 'Bye-bye!', audio: 'word_bye', successAudio: 'yes_bye', tone: 'blue',
  },
  apple: {
    id: 'apple', emoji: '🍎', label: 'apple', display: 'apple', audio: 'word_apple', successAudio: 'yes_apple', tone: 'red',
  },
  ball: {
    id: 'ball', emoji: '⚽', label: 'ball', display: 'ball', audio: 'word_ball', successAudio: 'yes_ball', tone: 'yellow',
  },
  cat: {
    id: 'cat', emoji: '🐱', label: 'cat', display: 'cat', audio: 'word_cat', successAudio: 'yes_cat', tone: 'purple',
  },
  dog: {
    id: 'dog', emoji: '🐶', label: 'dog', display: 'dog', audio: 'word_dog', successAudio: 'yes_dog', tone: 'green',
  },
  car: {
    id: 'car', emoji: '🚗', label: 'car', display: 'car', audio: 'word_car', successAudio: 'yes_car', tone: 'blue',
  },
  milk: {
    id: 'milk', emoji: '🥛', label: 'milk', display: 'milk', audio: 'word_milk', successAudio: 'yes_milk', tone: 'cream',
  },
  find: {
    id: 'find', emoji: '🔍', label: 'find', display: 'Find it!', audio: 'word_find', successAudio: 'yes_find', tone: 'blue',
  },
  give: {
    id: 'give', emoji: '👐', label: 'give', display: 'Give it!', audio: 'word_give', successAudio: 'yes_give', tone: 'yellow',
  },
  put: {
    id: 'put', emoji: '📥', label: 'put in', display: 'Put it in!', audio: 'word_put', successAudio: 'yes_put', tone: 'green',
  },
  jump: {
    id: 'jump', emoji: '⬆️', label: 'jump', display: 'Jump!', audio: 'word_jump', successAudio: 'yes_jump', tone: 'orange',
  },
  stop: {
    id: 'stop', emoji: '🛑', label: 'stop', display: 'Stop!', audio: 'word_stop', successAudio: 'yes_stop', tone: 'red',
  },
  red: {
    id: 'red', emoji: '🔴', label: 'red', display: 'red', audio: 'word_red', successAudio: 'yes_red', tone: 'red',
  },
  blue: {
    id: 'blue', emoji: '🔵', label: 'blue', display: 'blue', audio: 'word_blue', successAudio: 'yes_blue', tone: 'blue',
  },
  red_apple: {
    id: 'red_apple', emoji: '🔴🍎', label: 'red apple', display: 'red apple', audio: 'word_red_apple', successAudio: 'yes_red_apple', tone: 'red',
  },
  blue_ball: {
    id: 'blue_ball', emoji: '🔵⚽', label: 'blue ball', display: 'blue ball', audio: 'word_blue_ball', successAudio: 'yes_blue_ball', tone: 'blue',
  },
  red_ball: {
    id: 'red_ball', emoji: '🔴⚽', label: 'red ball', display: 'red ball', audio: 'word_red_ball', successAudio: 'yes_red_ball', tone: 'red',
  },
  blue_apple: {
    id: 'blue_apple', emoji: '🔵🍎', label: 'blue apple', display: 'blue apple', audio: 'word_blue_apple', successAudio: 'yes_blue_apple', tone: 'blue',
  },
  big: {
    id: 'big', emoji: '●', label: 'big', display: 'big', audio: 'word_big', successAudio: 'yes_big', tone: 'orange', scale: 'big',
  },
  small: {
    id: 'small', emoji: '●', label: 'small', display: 'small', audio: 'word_small', successAudio: 'yes_small', tone: 'purple', scale: 'small',
  },
  big_dog: {
    id: 'big_dog', emoji: '🐶', label: 'big dog', display: 'big dog', audio: 'word_big_dog', successAudio: 'yes_big_dog', tone: 'orange', scale: 'big',
  },
  small_cat: {
    id: 'small_cat', emoji: '🐱', label: 'small cat', display: 'small cat', audio: 'word_small_cat', successAudio: 'yes_small_cat', tone: 'purple', scale: 'small',
  },
  i_want: {
    id: 'i_want', emoji: '💭', label: 'I want…', display: 'I want…', audio: 'word_i_want', successAudio: 'yes_i_want', tone: 'orange',
  },
  want_apple: {
    id: 'want_apple', emoji: '🦊💭🍎', label: 'I want an apple', display: 'I want an apple.', audio: 'word_want_apple', successAudio: 'yes_want_apple', tone: 'red',
  },
  want_ball: {
    id: 'want_ball', emoji: '🦊💭⚽', label: 'I want a ball', display: 'I want a ball.', audio: 'word_want_ball', successAudio: 'yes_want_ball', tone: 'yellow',
  },
  want_milk: {
    id: 'want_milk', emoji: '🦊💭🥛', label: 'I want milk', display: 'I want milk.', audio: 'word_want_milk', successAudio: 'yes_want_milk', tone: 'cream',
  },
  here_you_are: {
    id: 'here_you_are', emoji: '👐🎁', label: 'Here you are', display: 'Here you are.', audio: 'word_here_you_are', successAudio: 'yes_here_you_are', tone: 'green',
  },
  thank_you: {
    id: 'thank_you', emoji: '🙏💛', label: 'Thank you', display: 'Thank you!', audio: 'word_thank_you', successAudio: 'yes_thank_you', tone: 'yellow',
  },
  i_like: {
    id: 'i_like', emoji: '💖', label: 'I like…', display: 'I like…', audio: 'word_i_like', successAudio: 'yes_i_like', tone: 'purple',
  },
  like_apples: {
    id: 'like_apples', emoji: '💖🍎', label: 'I like apples', display: 'I like apples.', audio: 'word_like_apples', successAudio: 'yes_like_apples', tone: 'red',
  },
  like_cats: {
    id: 'like_cats', emoji: '💖🐱', label: 'I like cats', display: 'I like cats.', audio: 'word_like_cats', successAudio: 'yes_like_cats', tone: 'purple',
  },
  like_milk: {
    id: 'like_milk', emoji: '💖🥛', label: 'I like milk', display: 'I like milk.', audio: 'word_like_milk', successAudio: 'yes_like_milk', tone: 'cream',
  },
  im_happy: {
    id: 'im_happy', emoji: '😊✨', label: "I'm happy", display: "I'm happy!", audio: 'word_im_happy', successAudio: 'yes_im_happy', tone: 'yellow',
  },
};

const MODE_LEARNING_ITEMS = {
  'forest-find': 'find',
  'forest-give': 'give',
  'forest-put': 'put',
  'town-want': 'i_want',
  'town-share': 'here_you_are',
  'town-thank': 'thank_you',
  'town-like': 'i_like',
  'town-feeling': 'im_happy',
  'castle-find': 'find',
  'castle-give': 'give',
  'castle-put': 'put',
};

export function getRoundLearningItems(roundData) {
  if (Array.isArray(roundData.learningItems) && roundData.learningItems.length) {
    return [...new Set(roundData.learningItems)];
  }
  return [...new Set([MODE_LEARNING_ITEMS[roundData.mode], roundData.target].filter(Boolean))];
}

const round = (target, choices, audio, prompt, mode = 'find', options = {}) => {
  const roundData = { target, choices, audio, prompt, mode, ...options };
  return { ...roundData, learningItems: getRoundLearningItems(roundData) };
};

export const MISSIONS = [
  {
    id: 1,
    stage: 0,
    title: '小狐醒来了',
    english: 'Hello!',
    icon: '🌞',
    storyGoal: '轻轻叫醒小狐，成为她的第一个朋友',
    scene: ['🌤️', '🛏️', '🦊'],
    introAudio: 'm01_story',
    meet: ['fox'],
    meetRepeats: 3,
    rounds: [round('fox', ['fox'], 'prompt_tap_foxy', 'Hello!', 'wake')],
    echo: 'fox',
    worldChange: '小狐的窗户亮起来了',
    worldEmoji: '🏡✨',
    keepsake: { emoji: '👋', title: 'Hello 小手' },
    familyQuest: '见到家人时挥挥手，说 “Hello!”',
  },
  {
    id: 2,
    stage: 0,
    title: '回声树洞',
    english: 'Hello?',
    icon: '🌳',
    storyGoal: '听回声，把藏起来的小狐找出来',
    scene: ['🌲', '🕳️', '🌼'],
    introAudio: 'm02_story',
    meet: ['fox'],
    meetRepeats: 2,
    rounds: [round('fox', ['fox'], 'prompt_find_foxy', 'Hello!', 'reveal')],
    echo: 'fox',
    worldChange: '树洞旁开出三朵回声花',
    worldEmoji: '🌳🌼',
    keepsake: { emoji: '🌼', title: '回声花' },
    familyQuest: '躲到门后说 “Hello”，让孩子来找你',
  },
  {
    id: 3,
    stage: 0,
    title: '晚安小路',
    english: 'Bye-bye!',
    icon: '🌙',
    storyGoal: '陪小狐走回家，挥手说再见',
    scene: ['🌙', '👣', '🏡'],
    introAudio: 'm03_story',
    meet: ['home'],
    meetRepeats: 3,
    rounds: [round('home', ['home'], 'prompt_bye', 'Bye-bye!', 'path')],
    echo: 'home',
    worldChange: '通往宝物花园的大门打开了',
    worldEmoji: '🚪🌟',
    keepsake: { emoji: '🌙', title: '月亮路灯' },
    familyQuest: '睡前和玩具挥挥手，说 “Bye-bye!”',
  },
  {
    id: 4,
    stage: 1,
    title: '苹果树醒来',
    english: 'Apple',
    icon: '🍎',
    storyGoal: '叫醒苹果树，让第一颗苹果落下来',
    scene: ['🌳', '🌱', '🦊'],
    introAudio: 'm04_story',
    meet: ['apple'],
    meetRepeats: 3,
    rounds: [round('apple', ['apple'], 'prompt_find_apple', 'Find the apple.', 'drop')],
    echo: 'apple',
    worldChange: '花园里长出第一棵苹果树',
    worldEmoji: '🌳🍎',
    keepsake: { emoji: '🍎', title: '第一颗苹果' },
    familyQuest: '吃水果时拿起苹果，说 “Apple.”',
  },
  {
    id: 5,
    stage: 1,
    title: '滚走的小球',
    english: 'Ball',
    icon: '⚽',
    storyGoal: '找到滚走的小球，把它送回篮子旁',
    scene: ['⛰️', '〰️', '🧺'],
    introAudio: 'm05_story',
    meet: ['ball'],
    meetRepeats: 3,
    rounds: [round('ball', ['apple', 'ball'], 'prompt_find_ball', 'Find the ball.', 'roll')],
    echo: 'ball',
    worldChange: '草坡上出现一条彩色球道',
    worldEmoji: '🌈⚽',
    keepsake: { emoji: '⚽', title: '滚滚小球' },
    familyQuest: '把球和另一个玩具放一起，说 “Ball.”',
  },
  {
    id: 6,
    stage: 1,
    title: '篮子里的宝物',
    english: 'Apple or ball?',
    icon: '🧺',
    storyGoal: '听声音，把两件宝物放进野餐篮',
    scene: ['🧺', '🍎', '⚽'],
    introAudio: 'm06_story',
    meet: ['apple', 'ball'],
    meetRepeats: 1,
    rounds: [
      round('apple', ['ball', 'apple'], 'prompt_find_apple', 'Find the apple.', 'pack'),
      round('ball', ['apple', 'ball'], 'prompt_find_ball', 'Find the ball.', 'pack'),
    ],
    echo: 'apple',
    worldChange: '野餐篮系上了漂亮的蝴蝶结',
    worldEmoji: '🧺🎀',
    keepsake: { emoji: '🎀', title: '宝物蝴蝶结' },
    familyQuest: '轮流说 “Apple” 和 “Ball”，让孩子指一指',
  },
  {
    id: 7,
    stage: 1,
    title: '草丛里的小猫',
    english: 'Cat',
    icon: '🐱',
    storyGoal: '听着喵喵声，把藏在草丛里的朋友找到',
    scene: ['🌿', '🌿', '🐾'],
    introAudio: 'm07_story',
    meet: ['cat'],
    meetRepeats: 3,
    rounds: [round('cat', ['apple', 'cat'], 'prompt_find_cat', 'Find the cat.', 'reveal')],
    echo: 'cat',
    worldChange: '小猫搬进了花园的小帐篷',
    worldEmoji: '⛺🐱',
    keepsake: { emoji: '🐾', title: '猫咪脚印' },
    familyQuest: '看到猫咪图片时，轻轻说 “Cat.”',
  },
  {
    id: 8,
    stage: 1,
    title: '泥坑小狗',
    english: 'Dog',
    icon: '🐶',
    storyGoal: '找到小狗，为它铺一条离开泥坑的小路',
    scene: ['☁️', '🟤', '👣'],
    introAudio: 'm08_story',
    meet: ['dog'],
    meetRepeats: 3,
    rounds: [round('dog', ['cat', 'dog'], 'prompt_find_dog', 'Find the dog.', 'rescue')],
    echo: 'dog',
    worldChange: '小狗洗干净，住进了花园',
    worldEmoji: '🫧🐶',
    keepsake: { emoji: '🫧', title: '泡泡毛巾' },
    familyQuest: '把猫和狗的图片放一起，说 “Dog.”',
  },
  {
    id: 9,
    stage: 1,
    title: '谁在叫我',
    english: 'Cat or dog?',
    icon: '🪧',
    storyGoal: '听一听，帮小猫和小狗找到自己的路牌',
    scene: ['🐱', '🪧', '🐶'],
    introAudio: 'm09_story',
    meet: ['cat', 'dog'],
    meetRepeats: 1,
    rounds: [
      round('cat', ['dog', 'cat'], 'prompt_find_cat', 'Find the cat.', 'sign'),
      round('dog', ['cat', 'dog'], 'prompt_find_dog', 'Find the dog.', 'sign'),
    ],
    echo: 'cat',
    worldChange: '两块动物路牌立在花园路口',
    worldEmoji: '🪧🐾',
    keepsake: { emoji: '🪧', title: '朋友路牌' },
    familyQuest: '说 “Cat” 或 “Dog”，孩子用动作模仿它',
  },
  {
    id: 10,
    stage: 1,
    title: '小车出发',
    english: 'Car',
    icon: '🚗',
    storyGoal: '找到小车，让它沿着新轨道开进花园',
    scene: ['🛤️', '🔧', '🏁'],
    introAudio: 'm10_story',
    meet: ['car'],
    meetRepeats: 3,
    rounds: [round('car', ['ball', 'car'], 'prompt_find_car', 'Find the car.', 'drive')],
    echo: 'car',
    worldChange: '一条小车轨道绕过花园',
    worldEmoji: '🛤️🚗',
    keepsake: { emoji: '🏁', title: '花园车票' },
    familyQuest: '玩小车时，让它出发并说 “Car.”',
  },
  {
    id: 11,
    stage: 1,
    title: '兔子的杯子',
    english: 'Milk',
    icon: '🥛',
    storyGoal: '找到牛奶，为口渴的兔子倒满杯子',
    scene: ['🐰', '🥤', '🌤️'],
    introAudio: 'm11_story',
    meet: ['milk'],
    meetRepeats: 3,
    rounds: [round('milk', ['apple', 'milk'], 'prompt_find_milk', 'Find the milk.', 'pour')],
    echo: 'milk',
    worldChange: '兔子的杯子变成花园小喷泉',
    worldEmoji: '🥛⛲',
    keepsake: { emoji: '🥛', title: '兔子牛奶杯' },
    familyQuest: '喝奶时举起杯子，说 “Milk.”',
  },
  {
    id: 12,
    stage: 1,
    title: '宝物躲猫猫',
    english: 'Treasure hunt',
    icon: '🎁',
    storyGoal: '从六种熟悉宝物里，找出小狐说的三个',
    scene: ['🎁', '❔', '🎁'],
    introAudio: 'm12_story',
    meet: ['apple', 'ball', 'cat', 'dog', 'car', 'milk'],
    meetRepeats: 1,
    rounds: [
      round('apple', ['ball', 'apple'], 'prompt_find_apple', 'Find the apple.', 'hide'),
      round('dog', ['cat', 'dog'], 'prompt_find_dog', 'Find the dog.', 'hide'),
      round('milk', ['car', 'milk'], 'prompt_find_milk', 'Find the milk.', 'hide'),
    ],
    echo: 'ball',
    worldChange: '花园里挂起一排宝物彩旗',
    worldEmoji: '🎏🎁',
    keepsake: { emoji: '🗝️', title: '宝物钥匙' },
    familyQuest: '从 apple、ball、cat 中任选两个玩听音寻找',
  },
  {
    id: 13,
    stage: 1,
    title: '夜晚手电筒',
    english: 'Listen in the dark',
    icon: '🔦',
    storyGoal: '在没有发光提示的夜晚，用耳朵寻找目标',
    scene: ['🌌', '🔦', '✨'],
    introAudio: 'm13_story',
    meet: ['cat', 'car', 'dog'],
    meetRepeats: 1,
    rounds: [
      round('cat', ['dog', 'car', 'cat'], 'prompt_find_cat', 'Find the cat.', 'flashlight'),
      round('car', ['cat', 'car', 'dog'], 'prompt_find_car', 'Find the car.', 'flashlight'),
      round('dog', ['car', 'dog', 'cat'], 'prompt_find_dog', 'Find the dog.', 'flashlight'),
    ],
    echo: 'cat',
    worldChange: '星星灯笼照亮了花园夜路',
    worldEmoji: '🏮⭐',
    keepsake: { emoji: '🔦', title: '星光手电筒' },
    familyQuest: '关小灯，用手电照两个玩具，说出其中一个英文',
  },
  {
    id: 14,
    stage: 1,
    title: '给朋友送礼物',
    english: 'Give me…',
    icon: '🎀',
    storyGoal: '听声音，把三件礼物送到朋友手中',
    scene: ['🐰', '🎁', '🦊'],
    introAudio: 'm14_story',
    meet: ['apple', 'ball', 'milk'],
    meetRepeats: 1,
    rounds: [
      round('ball', ['apple', 'ball', 'milk'], 'prompt_give_ball', 'Give me the ball.', 'gift'),
      round('milk', ['ball', 'milk', 'apple'], 'prompt_give_milk', 'Give me the milk.', 'gift'),
      round('apple', ['milk', 'apple', 'ball'], 'prompt_give_apple', 'Give me the apple.', 'gift'),
    ],
    echo: 'milk',
    worldChange: '庆典礼物桌摆满彩色礼盒',
    worldEmoji: '🎁🎀',
    keepsake: { emoji: '🎁', title: '朋友礼物盒' },
    familyQuest: '拿两件熟悉物品，说 “Give me the ball.”',
  },
  {
    id: 15,
    stage: 1,
    title: '花园庆典',
    english: 'Garden party!',
    icon: '🎉',
    storyGoal: '听懂三个线索，和所有朋友一起点亮庆典',
    scene: ['🎪', '🎈', '🎊'],
    introAudio: 'm15_story',
    meet: ['car', 'cat', 'milk'],
    meetRepeats: 1,
    rounds: [
      round('car', ['milk', 'cat', 'car'], 'prompt_find_car', 'Find the car.', 'festival'),
      round('cat', ['car', 'cat', 'milk'], 'prompt_find_cat', 'Find the cat.', 'festival'),
      round('milk', ['cat', 'milk', 'car'], 'prompt_find_milk', 'Find the milk.', 'festival'),
    ],
    echo: 'fox',
    worldChange: '宝物花园变成闪闪发光的庆典舞台',
    worldEmoji: '🎪🌈🎉',
    keepsake: { emoji: '🏆', title: '花园小英雄' },
    familyQuest: '从六个熟悉词中任选三个，玩一次家庭寻宝',
  },
  {
    id: 16,
    stage: 2,
    title: '会找东西的放大镜',
    english: 'Find it!',
    icon: '🔍',
    storyGoal: '跟着声音找到藏在森林入口的两块路标',
    scene: ['🌲', '🍂', '🔍'],
    introAudio: 'm16_story',
    meet: ['find'],
    meetRepeats: 3,
    rounds: [
      round('apple', ['ball', 'apple'], 'prompt_find_apple', 'Find the apple.', 'forest-find'),
      round('dog', ['cat', 'dog'], 'prompt_find_dog', 'Find the dog.', 'forest-find'),
    ],
    echo: 'find',
    worldChange: '行动森林的第一块路标亮起来了',
    worldEmoji: '🪧🔍',
    keepsake: { emoji: '🔍', title: '森林放大镜' },
    familyQuest: '藏好 apple 和 ball，说 “Find the apple.”',
  },
  {
    id: 17,
    stage: 2,
    title: '松鼠的野餐袋',
    english: 'Give it!',
    icon: '🐿️',
    storyGoal: '把松鼠需要的宝物递给它，装好野餐袋',
    scene: ['🐿️', '🎒', '🌰'],
    introAudio: 'm17_story',
    meet: ['give'],
    meetRepeats: 3,
    rounds: [
      round('ball', ['apple', 'ball'], 'prompt_give_ball', 'Give me the ball.', 'forest-give'),
      round('milk', ['milk', 'apple'], 'prompt_give_milk', 'Give me the milk.', 'forest-give'),
    ],
    echo: 'give',
    worldChange: '松鼠的野餐站挂起了欢迎旗',
    worldEmoji: '🐿️🎒',
    keepsake: { emoji: '🎒', title: '松鼠野餐袋' },
    familyQuest: '伸出手说 “Give me the ball.”，接到后开心道谢',
  },
  {
    id: 18,
    stage: 2,
    title: '树洞小车库',
    english: 'Put it in!',
    icon: '🕳️',
    storyGoal: '把小车和小球放进树洞，让森林小路恢复整洁',
    scene: ['🌳', '🕳️', '🚗'],
    introAudio: 'm18_story',
    meet: ['put'],
    meetRepeats: 3,
    rounds: [
      round('car', ['car'], 'prompt_put_car', 'Put the car in.', 'forest-put'),
      round('ball', ['car', 'ball'], 'prompt_put_ball', 'Put the ball in.', 'forest-put'),
    ],
    echo: 'put',
    worldChange: '大树长出一扇圆圆的车库门',
    worldEmoji: '🌳🚪',
    keepsake: { emoji: '🗝️', title: '树洞车库钥匙' },
    familyQuest: '拿一个盒子，说 “Put the car in.”',
  },
  {
    id: 19,
    stage: 2,
    title: '跳跳蘑菇',
    english: 'Jump!',
    icon: '🍄',
    storyGoal: '跟小狐一起跳起来，碰亮藏在树叶下的星星',
    scene: ['🍄', '🦊', '⭐'],
    introAudio: 'm19_story',
    meet: ['jump'],
    meetRepeats: 3,
    rounds: [round('jump', ['jump'], 'prompt_jump', 'Jump!', 'forest-action')],
    echo: 'jump',
    worldChange: '三朵弹弹蘑菇托起了星星灯',
    worldEmoji: '🍄⭐',
    keepsake: { emoji: '⬆️', title: '跳跳星星' },
    familyQuest: '一起听 “Jump!” 跳一下，笑一笑就结束',
  },
  {
    id: 20,
    stage: 2,
    title: '停下，落叶！',
    english: 'Stop!',
    icon: '🛑',
    storyGoal: '在落叶撞上小桥前，用声音让它们停下来',
    scene: ['🍂', '💨', '🌉'],
    introAudio: 'm20_story',
    meet: ['stop'],
    meetRepeats: 3,
    rounds: [round('stop', ['jump', 'stop'], 'prompt_stop', 'Stop!', 'forest-action')],
    echo: 'stop',
    worldChange: '小桥旁立起了一块红色安全牌',
    worldEmoji: '🌉🛑',
    keepsake: { emoji: '🛑', title: '落叶停止牌' },
    familyQuest: '玩走走停停：说 “Stop!” 时一起停住',
  },
  {
    id: 21,
    stage: 2,
    title: '会变的动作小路',
    english: 'Jump or stop?',
    icon: '👣',
    storyGoal: '听清楚蘑菇路的口令，跳过水坑并停在终点',
    scene: ['👣', '💧', '🏁'],
    introAudio: 'm21_story',
    meet: ['jump', 'stop'],
    meetRepeats: 1,
    rounds: [
      round('jump', ['stop', 'jump'], 'prompt_jump', 'Jump!', 'forest-action'),
      round('stop', ['jump', 'stop'], 'prompt_stop', 'Stop!', 'forest-action'),
    ],
    echo: 'jump',
    worldChange: '脚印小路一路亮到了森林深处',
    worldEmoji: '👣✨',
    keepsake: { emoji: '👣', title: '魔法动作脚印' },
    familyQuest: '轮流说 “Jump!” 和 “Stop!”，每次只做一个动作',
  },
  {
    id: 22,
    stage: 2,
    title: '红莓灯笼',
    english: 'Red',
    icon: '🔴',
    storyGoal: '找到红色魔法，让灰灰的浆果灯笼亮起来',
    scene: ['🫐', '🏮', '✨'],
    introAudio: 'm22_story',
    meet: ['red'],
    meetRepeats: 3,
    rounds: [round('red', ['red'], 'word_red', 'Red.', 'forest-color')],
    echo: 'red',
    worldChange: '森林入口挂起一串红莓灯笼',
    worldEmoji: '🔴🏮',
    keepsake: { emoji: '🔴', title: '红莓小灯' },
    familyQuest: '在家找一件红色东西，轻轻说 “Red.”',
  },
  {
    id: 23,
    stage: 2,
    title: '蓝色小溪',
    english: 'Blue',
    icon: '🔵',
    storyGoal: '找到蓝色魔法，为干涸的小溪铺上水色丝带',
    scene: ['🏞️', '〰️', '🎀'],
    introAudio: 'm23_story',
    meet: ['blue'],
    meetRepeats: 3,
    rounds: [round('blue', ['red', 'blue'], 'word_blue', 'Blue.', 'forest-color')],
    echo: 'blue',
    worldChange: '一条蓝色小溪流过森林草地',
    worldEmoji: '🔵💧',
    keepsake: { emoji: '💧', title: '蓝溪水滴' },
    familyQuest: '把一件红色和一件蓝色物品放一起，说 “Blue.”',
  },
  {
    id: 24,
    stage: 2,
    title: '彩石桥',
    english: 'Red or blue?',
    icon: '🌉',
    storyGoal: '听颜色，把两块彩石放回桥上，让朋友们过河',
    scene: ['🔴', '🌉', '🔵'],
    introAudio: 'm24_story',
    meet: ['red', 'blue'],
    meetRepeats: 1,
    rounds: [
      round('red', ['blue', 'red'], 'word_red', 'Red.', 'forest-color'),
      round('blue', ['red', 'blue'], 'word_blue', 'Blue.', 'forest-color'),
    ],
    echo: 'red',
    worldChange: '红蓝石桥连通了森林两岸',
    worldEmoji: '🌉🔴🔵',
    keepsake: { emoji: '🌉', title: '彩石桥徽章' },
    familyQuest: '说 “Red” 或 “Blue”，让孩子指向对应颜色',
  },
  {
    id: 25,
    stage: 2,
    title: '森林收拾队',
    english: 'Put it in',
    icon: '🧺',
    storyGoal: '听指令把露营宝物放进箱子，给大家腾出空地',
    scene: ['⛺', '📦', '🌲'],
    introAudio: 'm25_story',
    meet: ['put'],
    meetRepeats: 1,
    rounds: [
      round('apple', ['ball', 'apple'], 'prompt_put_apple', 'Put the apple in.', 'forest-put'),
      round('car', ['dog', 'car'], 'prompt_put_car', 'Put the car in.', 'forest-put'),
    ],
    echo: 'put',
    worldChange: '露营空地升起了一顶星星帐篷',
    worldEmoji: '⛺⭐',
    keepsake: { emoji: '📦', title: '收拾小箱子' },
    familyQuest: '收玩具时说一次 “Put the ball in.”',
  },
  {
    id: 26,
    stage: 2,
    title: '松鼠快递站',
    english: 'Give me…',
    icon: '📮',
    storyGoal: '听声音把两份快递送给等待的森林朋友',
    scene: ['🐿️', '📦', '📮'],
    introAudio: 'm26_story',
    meet: ['give'],
    meetRepeats: 1,
    rounds: [
      round('milk', ['apple', 'ball', 'milk'], 'prompt_give_milk', 'Give me the milk.', 'forest-give'),
      round('ball', ['milk', 'ball', 'apple'], 'prompt_give_ball', 'Give me the ball.', 'forest-give'),
    ],
    echo: 'give',
    worldChange: '树桩旁开张了一间松鼠快递站',
    worldEmoji: '🐿️📮',
    keepsake: { emoji: '📮', title: '森林快递章' },
    familyQuest: '让孩子从三个熟悉物品中递出你说的一个',
  },
  {
    id: 27,
    stage: 2,
    title: '萤火虫行动秀',
    english: 'Listen and move!',
    icon: '✨',
    storyGoal: '连续听懂三个声音线索，帮萤火虫点亮森林舞台',
    scene: ['🌌', '✨', '🎪'],
    introAudio: 'm27_story',
    meet: ['find', 'jump', 'stop'],
    meetRepeats: 1,
    rounds: [
      round('car', ['dog', 'milk', 'car'], 'prompt_find_car', 'Find the car.', 'forest-find'),
      round('jump', ['stop', 'jump'], 'prompt_jump', 'Jump!', 'forest-action'),
      round('stop', ['jump', 'stop'], 'prompt_stop', 'Stop!', 'forest-action'),
    ],
    echo: 'jump',
    worldChange: '行动森林变成了闪闪发光的萤火虫舞台',
    worldEmoji: '🌲✨🎪',
    keepsake: { emoji: '🏅', title: '森林行动英雄' },
    familyQuest: '玩三步小任务：Find the car → Jump → Stop',
  },
  {
    id: 28,
    stage: 3,
    title: '红苹果小径',
    english: 'Red apple',
    icon: '🍎',
    storyGoal: '把颜色和宝物连起来，点亮红苹果小路',
    scene: ['🔴', '🍎', '👣'],
    introAudio: 'm28_story',
    meet: ['red', 'apple', 'red_apple'],
    meetRepeats: 1,
    rounds: [
      round('red_apple', ['red_apple'], 'prompt_red_apple', 'Find the red apple.', 'valley-color'),
      round('red_apple', ['red_ball', 'red_apple'], 'prompt_red_apple', 'Find the red apple.', 'valley-color'),
    ],
    echo: 'red_apple',
    worldChange: '一串红苹果脚印铺进彩色山谷',
    worldEmoji: '🍎👣',
    keepsake: { emoji: '🍎', title: '红苹果路标' },
    familyQuest: '看到红苹果时，慢慢说 “Red apple.”',
  },
  {
    id: 29,
    stage: 3,
    title: '蓝球风车',
    english: 'Blue ball',
    icon: '🎡',
    storyGoal: '找到蓝色小球，让山谷风车转起来',
    scene: ['🔵', '⚽', '🎡'],
    introAudio: 'm29_story',
    meet: ['blue', 'ball', 'blue_ball'],
    meetRepeats: 1,
    rounds: [
      round('blue_ball', ['blue_ball'], 'prompt_blue_ball', 'Find the blue ball.', 'valley-color'),
      round('blue_ball', ['red_ball', 'blue_ball'], 'prompt_blue_ball', 'Find the blue ball.', 'valley-color'),
    ],
    echo: 'blue_ball',
    worldChange: '蓝色小球带着风车一起转起来',
    worldEmoji: '🔵🎡',
    keepsake: { emoji: '🎡', title: '蓝球小风车' },
    familyQuest: '找一个蓝色圆形物品，说 “Blue ball.”',
  },
  {
    id: 30,
    stage: 3,
    title: '颜色交换桥',
    english: 'Mix and match',
    icon: '🌈',
    storyGoal: '听清颜色和宝物，把交换后的伙伴送回桥上',
    scene: ['🔴⚽', '🌉', '🔵🍎'],
    introAudio: 'm30_story',
    meet: ['red_ball', 'blue_apple'],
    meetRepeats: 2,
    rounds: [
      round('red_ball', ['blue_ball', 'red_ball'], 'prompt_red_ball', 'Find the red ball.', 'valley-color'),
      round('blue_apple', ['red_apple', 'blue_apple'], 'prompt_blue_apple', 'Find the blue apple.', 'valley-color'),
      round('red_apple', ['blue_apple', 'red_ball', 'red_apple'], 'prompt_red_apple', 'Find the red apple.', 'valley-color'),
    ],
    echo: 'blue_apple',
    worldChange: '红蓝宝物排成一座会变色的桥',
    worldEmoji: '🌉🌈',
    keepsake: { emoji: '🧩', title: '颜色组合块' },
    familyQuest: '把红、蓝两色和两件玩具自由组合，说出其中一个',
  },
  {
    id: 31,
    stage: 3,
    title: '大脚印',
    english: 'Big dog',
    icon: '🐾',
    storyGoal: '顺着大脚印，找到躲在花丛后的大狗狗',
    scene: ['🐾', '🌼', '🐶'],
    introAudio: 'm31_story',
    meet: ['big', 'big_dog'],
    meetRepeats: 2,
    rounds: [
      round('big', ['big'], 'word_big', 'Big.', 'valley-size'),
      round('big_dog', ['dog', 'big_dog'], 'prompt_big_dog', 'Find the big dog.', 'valley-size'),
    ],
    echo: 'big_dog',
    worldChange: '大狗狗踩出一圈快乐的大脚印',
    worldEmoji: '🐶🐾',
    keepsake: { emoji: '🐾', title: '大大脚印章' },
    familyQuest: '找一大一小两个物品，指着大的说 “Big.”',
  },
  {
    id: 32,
    stage: 3,
    title: '小猫的秘密门',
    english: 'Small cat',
    icon: '🚪',
    storyGoal: '听懂大小线索，帮小猫打开刚刚好的秘密门',
    scene: ['🐱', '🚪', '✨'],
    introAudio: 'm32_story',
    meet: ['small', 'small_cat'],
    meetRepeats: 2,
    rounds: [
      round('small', ['big', 'small'], 'word_small', 'Small.', 'valley-size'),
      round('small_cat', ['cat', 'small_cat'], 'prompt_small_cat', 'Find the small cat.', 'valley-size'),
      round('big_dog', ['small_cat', 'big_dog'], 'prompt_big_dog', 'Find the big dog.', 'valley-size'),
    ],
    echo: 'small_cat',
    worldChange: '秘密门打开，彩色山谷亮起星星灯',
    worldEmoji: '🚪🌟',
    keepsake: { emoji: '🗝️', title: '小猫秘密钥匙' },
    familyQuest: '找一大一小两个玩具，轮流说 “Big” 和 “Small”',
  },
  {
    id: 33,
    stage: 4,
    title: '兔兔牛奶店',
    english: 'I want milk',
    icon: '🥛',
    storyGoal: '听懂兔兔想要什么，帮它在牛奶店下单',
    scene: ['🐰', '🏪', '🥛'],
    introAudio: 'm33_story',
    meet: ['i_want', 'want_milk'],
    meetRepeats: 2,
    rounds: [
      round('milk', ['milk'], 'prompt_want_milk', 'I want milk.', 'town-want', { scene: '🐰　💭　🏪' }),
    ],
    echo: 'want_milk',
    worldChange: '快乐小镇开了第一家牛奶店',
    worldEmoji: '🏪🥛',
    keepsake: { emoji: '🥛', title: '兔兔牛奶杯' },
    familyQuest: '吃点心时指一指牛奶，说 “I want milk.”',
  },
  {
    id: 34,
    stage: 4,
    title: '小球玩具车',
    english: 'I want a ball',
    icon: '🛒',
    storyGoal: '在玩具车上找到小狐想要的小球',
    scene: ['🛒', '⚽', '🦊'],
    introAudio: 'm34_story',
    meet: ['i_want', 'want_ball'],
    meetRepeats: 2,
    rounds: [
      round('ball', ['milk', 'ball'], 'prompt_want_ball', 'I want a ball.', 'town-want', { scene: '🦊　💭　🛒' }),
    ],
    echo: 'want_ball',
    worldChange: '玩具车挂起了一排小球彩灯',
    worldEmoji: '🛒⚽',
    keepsake: { emoji: '🎈', title: '小球气球' },
    familyQuest: '把球和杯子放在一起，说 “I want a ball.”',
  },
  {
    id: 35,
    stage: 4,
    title: '苹果小摊',
    english: 'I want an apple',
    icon: '🍎',
    storyGoal: '帮小猫在水果摊选到想要的苹果',
    scene: ['🐱', '🍎', '⛺'],
    introAudio: 'm35_story',
    meet: ['i_want', 'want_apple'],
    meetRepeats: 2,
    rounds: [
      round('apple', ['ball', 'apple'], 'prompt_want_apple', 'I want an apple.', 'town-want', { scene: '🐱　💭　🍎' }),
    ],
    echo: 'want_apple',
    worldChange: '水果摊的红白遮阳棚打开了',
    worldEmoji: '⛺🍎',
    keepsake: { emoji: '🧺', title: '苹果购物袋' },
    familyQuest: '吃水果前说一次 “I want an apple.”',
  },
  {
    id: 36,
    stage: 4,
    title: '三张心愿单',
    english: 'What do they want?',
    icon: '📜',
    storyGoal: '连续听三个心愿，把小镇快递送对地方',
    scene: ['📜', '🛵', '🏘️'],
    introAudio: 'm36_story',
    meet: ['want_milk', 'want_ball', 'want_apple'],
    meetRepeats: 1,
    rounds: [
      round('milk', ['apple', 'milk', 'ball'], 'prompt_want_milk', 'I want milk.', 'town-want', { scene: '🐰　💭　🥛' }),
      round('ball', ['milk', 'ball', 'apple'], 'prompt_want_ball', 'I want a ball.', 'town-want', { scene: '🐶　💭　⚽' }),
      round('apple', ['ball', 'apple', 'milk'], 'prompt_want_apple', 'I want an apple.', 'town-want', { scene: '🐱　💭　🍎' }),
    ],
    echo: 'i_want',
    worldChange: '一辆彩色快递车穿过小镇',
    worldEmoji: '🛵💨',
    keepsake: { emoji: '📜', title: '心愿清单' },
    familyQuest: '家长轮流说三个 I want 短句，让孩子递来对应物品',
  },
  {
    id: 37,
    stage: 4,
    title: '送给兔兔的礼物',
    english: 'Here you are',
    icon: '🎁',
    storyGoal: '把小狐的礼物亲手递给兔兔',
    scene: ['🦊', '🎁', '🐰'],
    introAudio: 'm37_story',
    meet: ['here_you_are'],
    meetRepeats: 3,
    rounds: [
      round('here_you_are', ['here_you_are'], 'prompt_here_you_are', 'Here you are.', 'town-share', { destination: '🐰　👐　🎁', destinationLabel: '把礼物递给兔兔' }),
    ],
    echo: 'here_you_are',
    worldChange: '兔兔家门口系上了感谢蝌蝶结',
    worldEmoji: '🐰🎀',
    keepsake: { emoji: '🎁', title: '分享小礼物' },
    familyQuest: '递给孩子一件小物品，说 “Here you are.”',
  },
  {
    id: 38,
    stage: 4,
    title: '野餐分享桌',
    english: 'Share with friends',
    icon: '🧺',
    storyGoal: '听声音选对食物，再亲手递给野餐朋友',
    scene: ['🧺', '🍎', '🐿️'],
    introAudio: 'm38_story',
    meet: ['here_you_are'],
    meetRepeats: 2,
    rounds: [
      round('apple', ['ball', 'apple'], 'prompt_here_apple', 'Here you are. An apple for you.', 'town-share', { destination: '🐿️　👐　🧺', destinationLabel: '把苹果递给松鼠' }),
      round('ball', ['apple', 'ball'], 'prompt_here_ball', 'Here you are. A ball for you.', 'town-share', { destination: '🐶　👐　⚽', destinationLabel: '把小球递给小狗' }),
    ],
    echo: 'here_you_are',
    worldChange: '小镇中央摆上了一张分享长桌',
    worldEmoji: '🧺🍎',
    keepsake: { emoji: '🧺', title: '分享野餐布' },
    familyQuest: '轮流递出苹果或球，每次说 “Here you are.”',
  },
  {
    id: 39,
    stage: 4,
    title: '友善小火车',
    english: 'Pass it along',
    icon: '🚂',
    storyGoal: '把两份礼物一站一站传给等待的朋友',
    scene: ['🚂', '🎁', '🐾'],
    introAudio: 'm39_story',
    meet: ['here_you_are'],
    meetRepeats: 1,
    rounds: [
      round('milk', ['ball', 'milk'], 'prompt_here_milk', 'Here you are. Milk for you.', 'town-share', { destination: '🐰　👐　🚂', destinationLabel: '把牛奶递给兔兔' }),
      round('ball', ['milk', 'ball', 'apple'], 'prompt_here_ball', 'Here you are. A ball for you.', 'town-share', { destination: '🐶　👐　🚂', destinationLabel: '把小球递给小狗' }),
    ],
    echo: 'here_you_are',
    worldChange: '友善火车开通了两座车站',
    worldEmoji: '🚂🌟',
    keepsake: { emoji: '🎫', title: '友善车票' },
    familyQuest: '三个人排成一队传玩具，传出时说 “Here you are.”',
  },
  {
    id: 40,
    stage: 4,
    title: '谢谢小铃铛',
    english: 'Thank you',
    icon: '🔔',
    storyGoal: '用一句友善的话，让沉睡的小铃铛响起来',
    scene: ['🙏', '🔔', '✨'],
    introAudio: 'm40_story',
    meet: ['thank_you'],
    meetRepeats: 3,
    rounds: [
      round('thank_you', ['thank_you'], 'prompt_thank_you', 'Thank you!', 'town-thank', { scene: '🎁　🔔　💛' }),
    ],
    echo: 'thank_you',
    worldChange: '小镇广场挂起一个金色谢谢铃',
    worldEmoji: '🔔💛',
    keepsake: { emoji: '🔔', title: '谢谢铃铛' },
    familyQuest: '家人递来东西后，说一次 “Thank you!”',
  },
  {
    id: 41,
    stage: 4,
    title: '会开花的话',
    english: 'Kind words',
    icon: '🌻',
    storyGoal: '在两句友善的话中听出谢谢，让花园开花',
    scene: ['🌱', '💬', '🌻'],
    introAudio: 'm41_story',
    meet: ['here_you_are', 'thank_you'],
    meetRepeats: 1,
    rounds: [
      round('thank_you', ['here_you_are', 'thank_you'], 'prompt_thank_you', 'Thank you!', 'town-thank', { scene: '💬　🌱　✨' }),
      round('here_you_are', ['thank_you', 'here_you_are'], 'prompt_here_you_are', 'Here you are.', 'town-share', { destination: '🦊　👐　🌻', destinationLabel: '把花递给小狐' }),
    ],
    echo: 'thank_you',
    worldChange: '谢谢花园开出了一圈太阳花',
    worldEmoji: '🌻💛',
    keepsake: { emoji: '🌻', title: '友善太阳花' },
    familyQuest: '玩“递给你”小游戏：Here you are → Thank you',
  },
  {
    id: 42,
    stage: 4,
    title: '小狐小商店',
    english: 'A little conversation',
    icon: '🏪',
    storyGoal: '用三步对话帮兔兔在小商店买到牛奶',
    scene: ['🐰', '🏪', '🦊'],
    introAudio: 'm42_story',
    meet: ['i_want', 'here_you_are', 'thank_you'],
    meetRepeats: 1,
    rounds: [
      round('milk', ['apple', 'milk'], 'prompt_want_milk', 'I want milk.', 'town-want', { scene: '🐰　💭　🏪' }),
      round('here_you_are', ['i_want', 'here_you_are'], 'prompt_here_you_are', 'Here you are.', 'town-share', { destination: '🐰　👐　🥛', destinationLabel: '把牛奶递给兔兔' }),
      round('thank_you', ['here_you_are', 'thank_you'], 'prompt_thank_you', 'Thank you!', 'town-thank', { scene: '🐰　💛　🦊' }),
    ],
    echo: 'thank_you',
    worldChange: '小狐商店亮起了温暖的橱窗灯',
    worldEmoji: '🏪💡',
    keepsake: { emoji: '🧾', title: '第一张小票' },
    familyQuest: '家长当店员，和孩子完成 I want → Here you are → Thank you',
  },
  {
    id: 43,
    stage: 4,
    title: '苹果心愿桌',
    english: 'I like apples',
    icon: '💖',
    storyGoal: '听懂小狐喜欢的食物，把它放上野餐桌',
    scene: ['🦊', '🧺', '🍎'],
    introAudio: 'm43_story',
    meet: ['i_like', 'like_apples'],
    meetRepeats: 2,
    rounds: [
      round('apple', ['ball', 'apple'], 'prompt_like_apples', 'I like apples.', 'town-like', { scene: '🦊　💖　🧺' }),
    ],
    echo: 'like_apples',
    worldChange: '野餐桌上摆满了红苹果花',
    worldEmoji: '🧺🍎',
    keepsake: { emoji: '💖', title: '苹果喜欢心' },
    familyQuest: '吃到喜欢的水果时，说 “I like apples.”',
  },
  {
    id: 44,
    stage: 4,
    title: '猫咪小茶馆',
    english: 'I like cats',
    icon: '🐱',
    storyGoal: '听一听小伙伴喜欢谁，邀请正确的动物进茶馆',
    scene: ['☕', '🐱', '🏠'],
    introAudio: 'm44_story',
    meet: ['i_like', 'like_cats'],
    meetRepeats: 2,
    rounds: [
      round('cat', ['dog', 'cat'], 'prompt_like_cats', 'I like cats.', 'town-like', { scene: '🐰　💖　☕' }),
    ],
    echo: 'like_cats',
    worldChange: '猫咪茶馆门口挂上了爪爪招牌',
    worldEmoji: '☕🐱',
    keepsake: { emoji: '🐾', title: '喜欢爪印' },
    familyQuest: '看到猫咪图片时，说 “I like cats.”',
  },
  {
    id: 45,
    stage: 4,
    title: '每人都喜欢',
    english: 'Everyone likes something',
    icon: '🎈',
    storyGoal: '听清两位朋友各自喜欢什么，装饰它们的小屋',
    scene: ['🏠', '💖', '🎈'],
    introAudio: 'm45_story',
    meet: ['like_apples', 'like_milk'],
    meetRepeats: 1,
    rounds: [
      round('milk', ['apple', 'milk'], 'prompt_like_milk', 'I like milk.', 'town-like', { scene: '🐰　💖　🏠' }),
      round('apple', ['milk', 'apple', 'ball'], 'prompt_like_apples', 'I like apples.', 'town-like', { scene: '🦊　💖　🏠' }),
    ],
    echo: 'i_like',
    worldChange: '两座朋友小屋挂上了自己喜欢的招牌',
    worldEmoji: '🏠💖',
    keepsake: { emoji: '🎈', title: '喜欢气球' },
    familyQuest: '家人各选一样喜欢的东西，用 “I like…” 说出来',
  },
  {
    id: 46,
    stage: 4,
    title: '微笑喷泉',
    english: "I'm happy",
    icon: '⛲',
    storyGoal: '找到快乐的表情，让小镇喷泉跳起来',
    scene: ['😊', '⛲', '✨'],
    introAudio: 'm46_story',
    meet: ['im_happy'],
    meetRepeats: 3,
    rounds: [
      round('im_happy', ['im_happy'], 'prompt_im_happy', "I'm happy!", 'town-feeling', { scene: '😊　⛲　✨' }),
      round('im_happy', ['thank_you', 'im_happy'], 'prompt_im_happy', "I'm happy!", 'town-feeling', { scene: '🎈　😊　🎶' }),
    ],
    echo: 'im_happy',
    worldChange: '微笑喷泉喷出了一道彩虹',
    worldEmoji: '⛲🌈',
    keepsake: { emoji: '😊', title: '快乐笑脸' },
    familyQuest: '开心的时候拍拍胸口，说 “I’m happy!”',
  },
  {
    id: 47,
    stage: 4,
    title: '快乐小镇节',
    english: 'Town festival',
    icon: '🎪',
    storyGoal: '完成一场五步节日对话，点亮小镇大舞台',
    scene: ['🎪', '🎆', '👭'],
    introAudio: 'm47_story',
    meet: ['i_want', 'here_you_are', 'thank_you', 'i_like', 'im_happy'],
    meetRepeats: 1,
    rounds: [
      round('milk', ['apple', 'milk'], 'prompt_want_milk', 'I want milk.', 'town-want', { scene: '🐰　💭　🎪' }),
      round('milk', ['milk'], 'prompt_here_milk', 'Here you are. Milk for you.', 'town-share', { destination: '🐰　👐　🥛', destinationLabel: '把牛奶递给兔兔' }),
      round('thank_you', ['here_you_are', 'thank_you'], 'prompt_thank_you', 'Thank you!', 'town-thank', { scene: '🐰　💛　🦊' }),
      round('apple', ['cat', 'apple'], 'prompt_like_apples', 'I like apples.', 'town-like', { scene: '🦊　💖　🍎' }),
      round('im_happy', ['thank_you', 'im_happy'], 'prompt_im_happy', "I'm happy!", 'town-feeling', { scene: '🎪　😊　🎆' }),
    ],
    echo: 'im_happy',
    worldChange: '快乐小镇节的大舞台全部点亮',
    worldEmoji: '🎪🎆',
    keepsake: { emoji: '🎖️', title: '小镇友善之星' },
    familyQuest: '用今天最喜欢的一句英语，和家人玩一轮角色扮演',
  },
  {
    id: 48,
    stage: 5,
    title: '沉睡的城堡门',
    english: 'Wake the castle',
    icon: '🏰',
    storyGoal: '先和守门朋友打招呼，再找到开门的红苹果',
    scene: ['🏰', '💤', '🍎'],
    introAudio: 'm48_story',
    meet: ['fox', 'red_apple', 'give'],
    meetRepeats: 1,
    rounds: [
      round('fox', ['home', 'fox'], 'prompt_tap_foxy', 'Hello!', 'castle-dialogue', { scene: '🏰　👋　🦊' }),
      round('red_apple', ['blue_apple', 'red_apple'], 'prompt_red_apple', 'Find the red apple.', 'castle-find', { scene: '🔑　🍎　🏰' }),
      round('apple', ['ball', 'apple'], 'prompt_give_apple', 'Give me the apple.', 'castle-give', { destination: '🧙　👐　🏰', destinationLabel: '把苹果递给守门人' }),
    ],
    echo: 'fox',
    worldChange: '故事城堡的大门缓缓打开',
    worldEmoji: '🏰🚪',
    keepsake: { emoji: '🔑', title: '红苹果钥匙' },
    familyQuest: '玩三步小故事：Hello → Find the red apple → Give me the apple',
  },
  {
    id: 49,
    stage: 5,
    title: '皇家野餐篮',
    english: 'Royal picnic',
    icon: '👑',
    storyGoal: '按顺序找到、递出并收好野餐宝物',
    scene: ['👑', '🧺', '🌿'],
    introAudio: 'm49_story',
    meet: ['blue_ball', 'milk', 'put'],
    meetRepeats: 1,
    rounds: [
      round('blue_ball', ['red_ball', 'blue_ball'], 'prompt_blue_ball', 'Find the blue ball.', 'castle-find', { scene: '👑　🔍　🌿' }),
      round('milk', ['apple', 'milk'], 'prompt_give_milk', 'Give me the milk.', 'castle-give', { destination: '🐰　👐　👑', destinationLabel: '把牛奶递给皇家兔兔' }),
      round('apple', ['ball', 'apple'], 'prompt_put_apple', 'Put the apple in.', 'castle-put', { destination: '🧺　📥　👑', destinationLabel: '把苹果放进野餐篮' }),
    ],
    echo: 'blue_ball',
    worldChange: '城堡草地铺开了皇家野餐布',
    worldEmoji: '👑🧺',
    keepsake: { emoji: '🍽️', title: '皇家野餐盘' },
    familyQuest: '让孩子听三步指令，每完成一步再说下一步',
  },
  {
    id: 50,
    stage: 5,
    title: '风门边的小猫',
    english: 'The lost little cat',
    icon: '🐱',
    storyGoal: '找到迷路的小猫，叫停大风，再送它回家',
    scene: ['🐱', '🌬️', '🚪'],
    introAudio: 'm50_story',
    meet: ['small_cat', 'stop', 'home'],
    meetRepeats: 1,
    rounds: [
      round('small_cat', ['big_dog', 'small_cat'], 'prompt_small_cat', 'Find the small cat.', 'castle-find', { scene: '🌬️　🔍　🐾' }),
      round('stop', ['jump', 'stop'], 'prompt_stop', 'Stop!', 'castle-action', { scene: '🌬️　🛑　🐱' }),
      round('home', ['fox', 'home'], 'prompt_bye', 'Bye-bye!', 'castle-dialogue', { scene: '🐱　👋　🏡' }),
    ],
    echo: 'home',
    worldChange: '小猫家的窗户亮起了星星灯',
    worldEmoji: '🐱🏡',
    keepsake: { emoji: '🌬️', title: '安静的风铃' },
    familyQuest: '用玩具演一遍 Find the small cat → Stop → Bye-bye',
  },
  {
    id: 51,
    stage: 5,
    title: '月亮小车库',
    english: 'Moon garage',
    icon: '🌙',
    storyGoal: '找到小车收进车库，再找回丢失的蓝球',
    scene: ['🌙', '🚗', '🏰'],
    introAudio: 'm51_story',
    meet: ['car', 'put', 'blue_ball'],
    meetRepeats: 1,
    rounds: [
      round('car', ['dog', 'car'], 'prompt_find_car', 'Find the car.', 'castle-find', { scene: '🌙　🔍　🛣️' }),
      round('car', ['car'], 'prompt_put_car', 'Put the car in.', 'castle-put', { destination: '🏰　📥　🌙', destinationLabel: '把小车放进月亮车库' }),
      round('blue_ball', ['blue_apple', 'blue_ball'], 'prompt_blue_ball', 'Find the blue ball.', 'castle-find', { scene: '🌙　🔍　💧' }),
    ],
    echo: 'blue_ball',
    worldChange: '月亮车库亮起蓝色小灯',
    worldEmoji: '🌙🚗',
    keepsake: { emoji: '🌙', title: '月亮车库灯' },
    familyQuest: '收玩具时玩 Find the car → Put the car in → Find the blue ball',
  },
  {
    id: 52,
    stage: 5,
    title: '小龙的早餐',
    english: 'Dragon breakfast',
    icon: '🐉',
    storyGoal: '听懂小龙想要的早餐，递给它，再听谢谢',
    scene: ['🐉', '🍽️', '🥛'],
    introAudio: 'm52_story',
    meet: ['want_milk', 'give', 'thank_you'],
    meetRepeats: 1,
    rounds: [
      round('milk', ['apple', 'milk'], 'prompt_want_milk', 'I want milk.', 'town-want', { scene: '🐉　💭　🍽️' }),
      round('milk', ['ball', 'milk'], 'prompt_give_milk', 'Give me the milk.', 'castle-give', { destination: '🐉　👐　🍽️', destinationLabel: '把牛奶递给小龙' }),
      round('thank_you', ['here_you_are', 'thank_you'], 'prompt_thank_you', 'Thank you!', 'town-thank', { scene: '🐉　💛　🥛' }),
    ],
    echo: 'thank_you',
    worldChange: '小龙厨房的烟囱冒出爱心云',
    worldEmoji: '🐉💛',
    keepsake: { emoji: '🍽️', title: '小龙早餐盘' },
    familyQuest: '玩早餐店：I want milk → Give me the milk → Thank you',
  },
  {
    id: 53,
    stage: 5,
    title: '彩虹房间',
    english: 'Rainbow room',
    icon: '🌈',
    storyGoal: '把四个变乱的颜色宝物依次送回彩虹架',
    scene: ['🌈', '🧩', '🏰'],
    introAudio: 'm53_story',
    meet: ['red_apple', 'blue_ball', 'red_ball', 'blue_apple'],
    meetRepeats: 1,
    rounds: [
      round('red_apple', ['blue_apple', 'red_apple'], 'prompt_red_apple', 'Find the red apple.', 'castle-find', { scene: '🔴　🌈　🍎' }),
      round('blue_ball', ['red_ball', 'blue_ball'], 'prompt_blue_ball', 'Find the blue ball.', 'castle-find', { scene: '🔵　🌈　⚽' }),
      round('red_ball', ['blue_ball', 'red_ball', 'red_apple'], 'prompt_red_ball', 'Find the red ball.', 'castle-find', { scene: '🔴　🌈　⚽' }),
      round('blue_apple', ['red_apple', 'blue_apple', 'blue_ball'], 'prompt_blue_apple', 'Find the blue apple.', 'castle-find', { scene: '🔵　🌈　🍎' }),
    ],
    echo: 'blue_apple',
    worldChange: '彩虹房间的四面墙同时亮了',
    worldEmoji: '🌈🧩',
    keepsake: { emoji: '🧩', title: '彩虹组合盒' },
    familyQuest: '用红蓝两色和两件玩具，玩四步听声选择',
  },
  {
    id: 54,
    stage: 5,
    title: '巨人门与小精灵门',
    english: 'Two magic doors',
    icon: '🚪',
    storyGoal: '先找大狗，再找小猫，帮它们打开合适的门',
    scene: ['🚪', '🐶', '🐱'],
    introAudio: 'm54_story',
    meet: ['big', 'small', 'big_dog', 'small_cat'],
    meetRepeats: 1,
    rounds: [
      round('big', ['small', 'big'], 'word_big', 'Big.', 'castle-size', { scene: '🚪　●　✨' }),
      round('big_dog', ['small_cat', 'big_dog'], 'prompt_big_dog', 'Find the big dog.', 'castle-find', { scene: '🚪　🔍　🐾' }),
      round('small_cat', ['big_dog', 'small_cat'], 'prompt_small_cat', 'Find the small cat.', 'castle-find', { scene: '🚪　🔍　✨' }),
    ],
    echo: 'small_cat',
    worldChange: '一大一小两扇魔法门都打开了',
    worldEmoji: '🚪✨',
    keepsake: { emoji: '🗝️', title: '两把魔法钥匙' },
    familyQuest: '把大小玩具当成两个角色，说 Big dog 和 Small cat',
  },
  {
    id: 55,
    stage: 5,
    title: '飞走的王冠',
    english: 'Catch the crown',
    icon: '👑',
    storyGoal: '听着三步动作口令，跳起、停住，再接住王冠',
    scene: ['🌬️', '👑', '🦊'],
    introAudio: 'm55_story',
    meet: ['jump', 'stop'],
    meetRepeats: 1,
    rounds: [
      round('jump', ['stop', 'jump'], 'prompt_jump', 'Jump!', 'castle-action', { scene: '👑　⬆️　🦊' }),
      round('stop', ['jump', 'stop'], 'prompt_stop', 'Stop!', 'castle-action', { scene: '🌬️　🛑　👑' }),
      round('jump', ['stop', 'jump'], 'prompt_jump', 'Jump!', 'castle-action', { scene: '🦊　⬆️　👑' }),
    ],
    echo: 'jump',
    worldChange: '王冠稳稳落在了星光展台上',
    worldEmoji: '👑⭐',
    keepsake: { emoji: '👑', title: '勇敢跳跳冠' },
    familyQuest: '轮流说 Jump → Stop → Jump，不加快、不比赛',
  },
  {
    id: 56,
    stage: 5,
    title: '城堡友谊商店',
    english: 'Friendship shop',
    icon: '🏪',
    storyGoal: '在新商店里问、递、说谢谢，完成一轮对话',
    scene: ['🏰', '🏪', '🎁'],
    introAudio: 'm56_story',
    meet: ['want_ball', 'here_you_are', 'thank_you', 'im_happy'],
    meetRepeats: 1,
    rounds: [
      round('ball', ['milk', 'ball'], 'prompt_want_ball', 'I want a ball.', 'town-want', { scene: '🧙　💭　🏪' }),
      round('ball', ['ball'], 'prompt_here_ball', 'Here you are. A ball for you.', 'town-share', { destination: '🧙　👐　⚽', destinationLabel: '把小球递给城堡朋友' }),
      round('thank_you', ['here_you_are', 'thank_you'], 'prompt_thank_you', 'Thank you!', 'town-thank', { scene: '🧙　💛　⚽' }),
      round('im_happy', ['thank_you', 'im_happy'], 'prompt_im_happy', "I'm happy!", 'town-feeling', { scene: '🏰　😊　🎁' }),
    ],
    echo: 'im_happy',
    worldChange: '友谊商店的门口亮起四颗爱心',
    worldEmoji: '🏪💞',
    keepsake: { emoji: '🛒', title: '友谊小购物车' },
    familyQuest: '换一个场景再玩 I want → Here you are → Thank you → I’m happy',
  },
  {
    id: 57,
    stage: 5,
    title: '秘密花园救援',
    english: 'Secret garden rescue',
    icon: '🌹',
    storyGoal: '先找小猫，再递牛奶，最后收好小球，救醒花园',
    scene: ['🌹', '🐱', '🔐'],
    introAudio: 'm57_story',
    meet: ['find', 'give', 'put'],
    meetRepeats: 1,
    rounds: [
      round('cat', ['dog', 'cat', 'car'], 'prompt_find_cat', 'Find the cat.', 'castle-find', { scene: '🌹　🔍　🐾' }),
      round('milk', ['apple', 'milk'], 'prompt_give_milk', 'Give me the milk.', 'castle-give', { destination: '🐱　👐　🌹', destinationLabel: '把牛奶递给小猫' }),
      round('ball', ['car', 'ball'], 'prompt_put_ball', 'Put the ball in.', 'castle-put', { destination: '📦　📥　🌹', destinationLabel: '把小球放进花园宝箱' }),
    ],
    echo: 'put',
    worldChange: '秘密花园的玫瑰一起开放',
    worldEmoji: '🌹✨',
    keepsake: { emoji: '🌹', title: '秘密玫瑰' },
    familyQuest: '用三件玩具讲一个 Find → Give → Put 的小故事',
  },
  {
    id: 58,
    stage: 5,
    title: '城堡喜欢派对',
    english: 'Favorite party',
    icon: '🎉',
    storyGoal: '听懂客人喜欢什么，送上正确的装饰，看看心情',
    scene: ['🎉', '💖', '🏰'],
    introAudio: 'm58_story',
    meet: ['like_apples', 'like_cats', 'im_happy'],
    meetRepeats: 1,
    rounds: [
      round('apple', ['ball', 'apple'], 'prompt_like_apples', 'I like apples.', 'town-like', { scene: '🦊　💖　🎉' }),
      round('cat', ['dog', 'cat'], 'prompt_like_cats', 'I like cats.', 'town-like', { scene: '🐰　💖　🎉' }),
      round('im_happy', ['thank_you', 'im_happy'], 'prompt_im_happy', "I'm happy!", 'town-feeling', { scene: '🏰　😊　🎉' }),
    ],
    echo: 'im_happy',
    worldChange: '城堡舞厅飘起了喜欢心气球',
    worldEmoji: '🎉💖',
    keepsake: { emoji: '💖', title: '派对喜欢心' },
    familyQuest: '轮流说 I like apples / cats，最后一起说 I’m happy',
  },
  {
    id: 59,
    stage: 5,
    title: '友谊之星大结局',
    english: 'Friendship Star',
    icon: '🌟',
    storyGoal: '用熟悉的招呼、线索和对话，点亮英语岛友谊之星',
    scene: ['🏰', '🌟', '🦊'],
    introAudio: 'm59_story',
    meet: ['fox', 'red_apple', 'want_milk', 'here_you_are', 'thank_you', 'im_happy'],
    meetRepeats: 1,
    rounds: [
      round('fox', ['home', 'fox'], 'prompt_tap_foxy', 'Hello!', 'castle-dialogue', { scene: '🌟　👋　🏰' }),
      round('red_apple', ['blue_apple', 'red_apple'], 'prompt_red_apple', 'Find the red apple.', 'castle-find', { scene: '🌟　🔍　🍎' }),
      round('milk', ['apple', 'milk'], 'prompt_want_milk', 'I want milk.', 'town-want', { scene: '🐰　💭　🌟' }),
      round('milk', ['milk'], 'prompt_here_milk', 'Here you are. Milk for you.', 'town-share', { destination: '🐰　👐　🥛', destinationLabel: '把牛奶递给兔兔' }),
      round('thank_you', ['here_you_are', 'thank_you'], 'prompt_thank_you', 'Thank you!', 'town-thank', { scene: '🐰　💛　🌟' }),
      round('im_happy', ['thank_you', 'im_happy'], 'prompt_im_happy', "I'm happy!", 'town-feeling', { scene: '🦊　😊　🌟' }),
    ],
    echo: 'im_happy',
    worldChange: '英语岛上空亮起了永远的友谊之星',
    worldEmoji: '🌟🏰🦊',
    keepsake: { emoji: '🌟', title: '友谊之星' },
    familyQuest: '让孩子选一个最喜欢的故事重玩，庆祝她听懂了英语',
  },
];

export const STAGES = [
  {
    id: 0,
    title: '小狐之家',
    english: 'Foxy Home',
    icon: '🏡',
    description: '先学会听声音、点一点击和回到地图',
    color: '#ff9f68',
  },
  {
    id: 1,
    title: '宝物花园',
    english: 'Treasure Garden',
    icon: '🌼',
    description: '用耳朵认识 apple、ball、cat、dog、car 和 milk',
    color: '#63c982',
  },
  {
    id: 2,
    title: '行动森林',
    english: 'Action Forest',
    icon: '🌲',
    description: '听懂 find、give、put、jump、stop、red 和 blue，并马上行动',
    color: '#4fa875',
  },
  {
    id: 3,
    title: '彩色山谷',
    english: 'Color Valley',
    icon: '🌈',
    description: '把熟悉的颜色、宝物和大小拼成 red apple、blue ball、big dog 与 small cat',
    color: '#b784df',
  },
  {
    id: 4,
    title: '快乐小镇',
    english: 'Happy Town',
    icon: '🏘️',
    description: '用 I want、Here you are、Thank you、I like 和 I’m happy 完成真正交流',
    color: '#f2ad67',
  },
  {
    id: 5,
    title: '故事城堡',
    english: 'Story Castle',
    icon: '🏰',
    description: '把熟悉的英语连成三到四步小故事，最后挑战六步终章',
    color: '#7d83d8',
  },
];

export function getMission(id) {
  return MISSIONS.find((mission) => mission.id === id);
}

export function getVoiceText(key) {
  return VOICE_LINES[key]?.text || '';
}
